// Code generated by ent, DO NOT EDIT.

package reportdataset

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the reportdataset type in the database.
	Label = "report_dataset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGeneratedAt holds the string denoting the generated_at field in the database.
	FieldGeneratedAt = "generated_at"
	// FieldRankingPolicyID holds the string denoting the ranking_policy_id field in the database.
	FieldRankingPolicyID = "ranking_policy_id"
	// FieldRankingPolicyVersion holds the string denoting the ranking_policy_version field in the database.
	FieldRankingPolicyVersion = "ranking_policy_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCanonical holds the string denoting the canonical field in the database.
	FieldCanonical = "canonical"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the reportdataset in the database.
	Table = "report_datasets"
)

// Columns holds all SQL columns for reportdataset fields.
var Columns = []string{
	FieldID,
	FieldGeneratedAt,
	FieldRankingPolicyID,
	FieldRankingPolicyVersion,
	FieldStatus,
	FieldCanonical,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RankingPolicyIDValidator is a validator for the "ranking_policy_id" field. It is called by the builders before save.
	RankingPolicyIDValidator func(string) error
	// RankingPolicyVersionValidator is a validator for the "ranking_policy_version" field. It is called by the builders before save.
	RankingPolicyVersionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ReportDataset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGeneratedAt orders the results by the generated_at field.
func ByGeneratedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneratedAt, opts...).ToFunc()
}

// ByRankingPolicyID orders the results by the ranking_policy_id field.
func ByRankingPolicyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRankingPolicyID, opts...).ToFunc()
}

// ByRankingPolicyVersion orders the results by the ranking_policy_version field.
func ByRankingPolicyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRankingPolicyVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
