// Code generated by ent, DO NOT EDIT.

package itemaugment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldProvider, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldSourceRef, v))
}

// Moscow applies equality check predicate on the "moscow" field. It's identical to MoscowEQ.
func Moscow(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldMoscow, v))
}

// Kano applies equality check predicate on the "kano" field. It's identical to KanoEQ.
func Kano(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldKano, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldNotes, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldProvider, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldSourceRef, v))
}

// MoscowEQ applies the EQ predicate on the "moscow" field.
func MoscowEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldMoscow, v))
}

// MoscowNEQ applies the NEQ predicate on the "moscow" field.
func MoscowNEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldMoscow, v))
}

// MoscowIn applies the In predicate on the "moscow" field.
func MoscowIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldMoscow, vs...))
}

// MoscowNotIn applies the NotIn predicate on the "moscow" field.
func MoscowNotIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldMoscow, vs...))
}

// MoscowGT applies the GT predicate on the "moscow" field.
func MoscowGT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldMoscow, v))
}

// MoscowGTE applies the GTE predicate on the "moscow" field.
func MoscowGTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldMoscow, v))
}

// MoscowLT applies the LT predicate on the "moscow" field.
func MoscowLT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldMoscow, v))
}

// MoscowLTE applies the LTE predicate on the "moscow" field.
func MoscowLTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldMoscow, v))
}

// MoscowContains applies the Contains predicate on the "moscow" field.
func MoscowContains(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContains(FieldMoscow, v))
}

// MoscowHasPrefix applies the HasPrefix predicate on the "moscow" field.
func MoscowHasPrefix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasPrefix(FieldMoscow, v))
}

// MoscowHasSuffix applies the HasSuffix predicate on the "moscow" field.
func MoscowHasSuffix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasSuffix(FieldMoscow, v))
}

// MoscowIsNil applies the IsNil predicate on the "moscow" field.
func MoscowIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldMoscow))
}

// MoscowNotNil applies the NotNil predicate on the "moscow" field.
func MoscowNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldMoscow))
}

// MoscowEqualFold applies the EqualFold predicate on the "moscow" field.
func MoscowEqualFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldMoscow, v))
}

// MoscowContainsFold applies the ContainsFold predicate on the "moscow" field.
func MoscowContainsFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldMoscow, v))
}

// KanoEQ applies the EQ predicate on the "kano" field.
func KanoEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldKano, v))
}

// KanoNEQ applies the NEQ predicate on the "kano" field.
func KanoNEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldKano, v))
}

// KanoIn applies the In predicate on the "kano" field.
func KanoIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldKano, vs...))
}

// KanoNotIn applies the NotIn predicate on the "kano" field.
func KanoNotIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldKano, vs...))
}

// KanoGT applies the GT predicate on the "kano" field.
func KanoGT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldKano, v))
}

// KanoGTE applies the GTE predicate on the "kano" field.
func KanoGTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldKano, v))
}

// KanoLT applies the LT predicate on the "kano" field.
func KanoLT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldKano, v))
}

// KanoLTE applies the LTE predicate on the "kano" field.
func KanoLTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldKano, v))
}

// KanoContains applies the Contains predicate on the "kano" field.
func KanoContains(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContains(FieldKano, v))
}

// KanoHasPrefix applies the HasPrefix predicate on the "kano" field.
func KanoHasPrefix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasPrefix(FieldKano, v))
}

// KanoHasSuffix applies the HasSuffix predicate on the "kano" field.
func KanoHasSuffix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasSuffix(FieldKano, v))
}

// KanoIsNil applies the IsNil predicate on the "kano" field.
func KanoIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldKano))
}

// KanoNotNil applies the NotNil predicate on the "kano" field.
func KanoNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldKano))
}

// KanoEqualFold applies the EqualFold predicate on the "kano" field.
func KanoEqualFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldKano, v))
}

// KanoContainsFold applies the ContainsFold predicate on the "kano" field.
func KanoContainsFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldKano, v))
}

// RiceIsNil applies the IsNil predicate on the "rice" field.
func RiceIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldRice))
}

// RiceNotNil applies the NotNil predicate on the "rice" field.
func RiceNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldRice))
}

// OkrRefsIsNil applies the IsNil predicate on the "okr_refs" field.
func OkrRefsIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldOkrRefs))
}

// OkrRefsNotNil applies the NotNil predicate on the "okr_refs" field.
func OkrRefsNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldOkrRefs))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldContainsFold(FieldNotes, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotNull(FieldMetadata))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ItemAugment {
	return predicate.ItemAugment(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemAugment) predicate.ItemAugment {
	return predicate.ItemAugment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemAugment) predicate.ItemAugment {
	return predicate.ItemAugment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemAugment) predicate.ItemAugment {
	return predicate.ItemAugment(sql.NotPredicates(p))
}
