// Code generated by ent, DO NOT EDIT.

package release

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldProvider, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceID, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceRef, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceURL, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldName, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStartDate, v))
}

// ReleaseDate applies equality check predicate on the "release_date" field. It's identical to ReleaseDateEQ.
func ReleaseDate(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldReleaseDate, v))
}

// Released applies equality check predicate on the "released" field. It's identical to ReleasedEQ.
func Released(v bool) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldReleased, v))
}

// StatusID applies equality check predicate on the "status_id" field. It's identical to StatusIDEQ.
func StatusID(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusID, v))
}

// StatusName applies equality check predicate on the "status_name" field. It's identical to StatusNameEQ.
func StatusName(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusName, v))
}

// StatusCategory applies equality check predicate on the "status_category" field. It's identical to StatusCategoryEQ.
func StatusCategory(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusCategory, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v float64) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldProgress, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSyncedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldProvider, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldSourceID, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldSourceRef, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldSourceURL, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldName, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldStartDate))
}

// ReleaseDateEQ applies the EQ predicate on the "release_date" field.
func ReleaseDateEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldReleaseDate, v))
}

// ReleaseDateNEQ applies the NEQ predicate on the "release_date" field.
func ReleaseDateNEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldReleaseDate, v))
}

// ReleaseDateIn applies the In predicate on the "release_date" field.
func ReleaseDateIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldReleaseDate, vs...))
}

// ReleaseDateNotIn applies the NotIn predicate on the "release_date" field.
func ReleaseDateNotIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldReleaseDate, vs...))
}

// ReleaseDateGT applies the GT predicate on the "release_date" field.
func ReleaseDateGT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldReleaseDate, v))
}

// ReleaseDateGTE applies the GTE predicate on the "release_date" field.
func ReleaseDateGTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldReleaseDate, v))
}

// ReleaseDateLT applies the LT predicate on the "release_date" field.
func ReleaseDateLT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldReleaseDate, v))
}

// ReleaseDateLTE applies the LTE predicate on the "release_date" field.
func ReleaseDateLTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldReleaseDate, v))
}

// ReleaseDateIsNil applies the IsNil predicate on the "release_date" field.
func ReleaseDateIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldReleaseDate))
}

// ReleaseDateNotNil applies the NotNil predicate on the "release_date" field.
func ReleaseDateNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldReleaseDate))
}

// ReleasedEQ applies the EQ predicate on the "released" field.
func ReleasedEQ(v bool) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldReleased, v))
}

// ReleasedNEQ applies the NEQ predicate on the "released" field.
func ReleasedNEQ(v bool) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldReleased, v))
}

// StatusIDEQ applies the EQ predicate on the "status_id" field.
func StatusIDEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusID, v))
}

// StatusIDNEQ applies the NEQ predicate on the "status_id" field.
func StatusIDNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldStatusID, v))
}

// StatusIDIn applies the In predicate on the "status_id" field.
func StatusIDIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldStatusID, vs...))
}

// StatusIDNotIn applies the NotIn predicate on the "status_id" field.
func StatusIDNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldStatusID, vs...))
}

// StatusIDGT applies the GT predicate on the "status_id" field.
func StatusIDGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldStatusID, v))
}

// StatusIDGTE applies the GTE predicate on the "status_id" field.
func StatusIDGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldStatusID, v))
}

// StatusIDLT applies the LT predicate on the "status_id" field.
func StatusIDLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldStatusID, v))
}

// StatusIDLTE applies the LTE predicate on the "status_id" field.
func StatusIDLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldStatusID, v))
}

// StatusIDContains applies the Contains predicate on the "status_id" field.
func StatusIDContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldStatusID, v))
}

// StatusIDHasPrefix applies the HasPrefix predicate on the "status_id" field.
func StatusIDHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldStatusID, v))
}

// StatusIDHasSuffix applies the HasSuffix predicate on the "status_id" field.
func StatusIDHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldStatusID, v))
}

// StatusIDIsNil applies the IsNil predicate on the "status_id" field.
func StatusIDIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldStatusID))
}

// StatusIDNotNil applies the NotNil predicate on the "status_id" field.
func StatusIDNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldStatusID))
}

// StatusIDEqualFold applies the EqualFold predicate on the "status_id" field.
func StatusIDEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldStatusID, v))
}

// StatusIDContainsFold applies the ContainsFold predicate on the "status_id" field.
func StatusIDContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldStatusID, v))
}

// StatusNameEQ applies the EQ predicate on the "status_name" field.
func StatusNameEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusName, v))
}

// StatusNameNEQ applies the NEQ predicate on the "status_name" field.
func StatusNameNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldStatusName, v))
}

// StatusNameIn applies the In predicate on the "status_name" field.
func StatusNameIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldStatusName, vs...))
}

// StatusNameNotIn applies the NotIn predicate on the "status_name" field.
func StatusNameNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldStatusName, vs...))
}

// StatusNameGT applies the GT predicate on the "status_name" field.
func StatusNameGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldStatusName, v))
}

// StatusNameGTE applies the GTE predicate on the "status_name" field.
func StatusNameGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldStatusName, v))
}

// StatusNameLT applies the LT predicate on the "status_name" field.
func StatusNameLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldStatusName, v))
}

// StatusNameLTE applies the LTE predicate on the "status_name" field.
func StatusNameLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldStatusName, v))
}

// StatusNameContains applies the Contains predicate on the "status_name" field.
func StatusNameContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldStatusName, v))
}

// StatusNameHasPrefix applies the HasPrefix predicate on the "status_name" field.
func StatusNameHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldStatusName, v))
}

// StatusNameHasSuffix applies the HasSuffix predicate on the "status_name" field.
func StatusNameHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldStatusName, v))
}

// StatusNameIsNil applies the IsNil predicate on the "status_name" field.
func StatusNameIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldStatusName))
}

// StatusNameNotNil applies the NotNil predicate on the "status_name" field.
func StatusNameNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldStatusName))
}

// StatusNameEqualFold applies the EqualFold predicate on the "status_name" field.
func StatusNameEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldStatusName, v))
}

// StatusNameContainsFold applies the ContainsFold predicate on the "status_name" field.
func StatusNameContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldStatusName, v))
}

// StatusCategoryEQ applies the EQ predicate on the "status_category" field.
func StatusCategoryEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldStatusCategory, v))
}

// StatusCategoryNEQ applies the NEQ predicate on the "status_category" field.
func StatusCategoryNEQ(v string) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldStatusCategory, v))
}

// StatusCategoryIn applies the In predicate on the "status_category" field.
func StatusCategoryIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldStatusCategory, vs...))
}

// StatusCategoryNotIn applies the NotIn predicate on the "status_category" field.
func StatusCategoryNotIn(vs ...string) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldStatusCategory, vs...))
}

// StatusCategoryGT applies the GT predicate on the "status_category" field.
func StatusCategoryGT(v string) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldStatusCategory, v))
}

// StatusCategoryGTE applies the GTE predicate on the "status_category" field.
func StatusCategoryGTE(v string) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldStatusCategory, v))
}

// StatusCategoryLT applies the LT predicate on the "status_category" field.
func StatusCategoryLT(v string) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldStatusCategory, v))
}

// StatusCategoryLTE applies the LTE predicate on the "status_category" field.
func StatusCategoryLTE(v string) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldStatusCategory, v))
}

// StatusCategoryContains applies the Contains predicate on the "status_category" field.
func StatusCategoryContains(v string) predicate.Release {
	return predicate.Release(sql.FieldContains(FieldStatusCategory, v))
}

// StatusCategoryHasPrefix applies the HasPrefix predicate on the "status_category" field.
func StatusCategoryHasPrefix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasPrefix(FieldStatusCategory, v))
}

// StatusCategoryHasSuffix applies the HasSuffix predicate on the "status_category" field.
func StatusCategoryHasSuffix(v string) predicate.Release {
	return predicate.Release(sql.FieldHasSuffix(FieldStatusCategory, v))
}

// StatusCategoryIsNil applies the IsNil predicate on the "status_category" field.
func StatusCategoryIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldStatusCategory))
}

// StatusCategoryNotNil applies the NotNil predicate on the "status_category" field.
func StatusCategoryNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldStatusCategory))
}

// StatusCategoryEqualFold applies the EqualFold predicate on the "status_category" field.
func StatusCategoryEqualFold(v string) predicate.Release {
	return predicate.Release(sql.FieldEqualFold(FieldStatusCategory, v))
}

// StatusCategoryContainsFold applies the ContainsFold predicate on the "status_category" field.
func StatusCategoryContainsFold(v string) predicate.Release {
	return predicate.Release(sql.FieldContainsFold(FieldStatusCategory, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v float64) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v float64) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...float64) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...float64) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v float64) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v float64) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v float64) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v float64) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldProgress, v))
}

// ProgressIsNil applies the IsNil predicate on the "progress" field.
func ProgressIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldProgress))
}

// ProgressNotNil applies the NotNil predicate on the "progress" field.
func ProgressNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldProgress))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Release {
	return predicate.Release(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Release {
	return predicate.Release(sql.FieldNotNull(FieldMetadata))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.Release {
	return predicate.Release(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.Release {
	return predicate.Release(sql.FieldLTE(FieldSyncedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Release) predicate.Release {
	return predicate.Release(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Release) predicate.Release {
	return predicate.Release(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Release) predicate.Release {
	return predicate.Release(sql.NotPredicates(p))
}
