// Code generated by ent, DO NOT EDIT.

package opportunityassessment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldID, id))
}

// OpportunitySpecID applies equality check predicate on the "opportunity_spec_id" field. It's identical to OpportunitySpecIDEQ.
func OpportunitySpecID(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunitySpecID, v))
}

// RmiID applies equality check predicate on the "rmi_id" field. It's identical to RmiIDEQ.
func RmiID(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRmiID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldTitle, v))
}

// CycleNumber applies equality check predicate on the "cycle_number" field. It's identical to CycleNumberEQ.
func CycleNumber(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCycleNumber, v))
}

// AssessedAt applies equality check predicate on the "assessed_at" field. It's identical to AssessedAtEQ.
func AssessedAt(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldAssessedAt, v))
}

// SupersedesID applies equality check predicate on the "supersedes_id" field. It's identical to SupersedesIDEQ.
func SupersedesID(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldSupersedesID, v))
}

// Current applies equality check predicate on the "current" field. It's identical to CurrentEQ.
func Current(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCurrent, v))
}

// MoscowClass applies equality check predicate on the "moscow_class" field. It's identical to MoscowClassEQ.
func MoscowClass(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldMoscowClass, v))
}

// RiceScore applies equality check predicate on the "rice_score" field. It's identical to RiceScoreEQ.
func RiceScore(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRiceScore, v))
}

// RiceComputable applies equality check predicate on the "rice_computable" field. It's identical to RiceComputableEQ.
func RiceComputable(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRiceComputable, v))
}

// OpportunityRankCalculated applies equality check predicate on the "opportunity_rank_calculated" field. It's identical to OpportunityRankCalculatedEQ.
func OpportunityRankCalculated(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunityRankCalculated, v))
}

// OpportunityRankFinal applies equality check predicate on the "opportunity_rank_final" field. It's identical to OpportunityRankFinalEQ.
func OpportunityRankFinal(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunityRankFinal, v))
}

// KanoCategory applies equality check predicate on the "kano_category" field. It's identical to KanoCategoryEQ.
func KanoCategory(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldKanoCategory, v))
}

// MihCategory applies equality check predicate on the "mih_category" field. It's identical to MihCategoryEQ.
func MihCategory(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldMihCategory, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldUpdatedAt, v))
}

// OpportunitySpecIDEQ applies the EQ predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDNEQ applies the NEQ predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDIn applies the In predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldOpportunitySpecID, vs...))
}

// OpportunitySpecIDNotIn applies the NotIn predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldOpportunitySpecID, vs...))
}

// OpportunitySpecIDGT applies the GT predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDGTE applies the GTE predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDLT applies the LT predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDLTE applies the LTE predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDContains applies the Contains predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDHasPrefix applies the HasPrefix predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDHasSuffix applies the HasSuffix predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDEqualFold applies the EqualFold predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldOpportunitySpecID, v))
}

// OpportunitySpecIDContainsFold applies the ContainsFold predicate on the "opportunity_spec_id" field.
func OpportunitySpecIDContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldOpportunitySpecID, v))
}

// RmiIDEQ applies the EQ predicate on the "rmi_id" field.
func RmiIDEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRmiID, v))
}

// RmiIDNEQ applies the NEQ predicate on the "rmi_id" field.
func RmiIDNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldRmiID, v))
}

// RmiIDIn applies the In predicate on the "rmi_id" field.
func RmiIDIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldRmiID, vs...))
}

// RmiIDNotIn applies the NotIn predicate on the "rmi_id" field.
func RmiIDNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldRmiID, vs...))
}

// RmiIDGT applies the GT predicate on the "rmi_id" field.
func RmiIDGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldRmiID, v))
}

// RmiIDGTE applies the GTE predicate on the "rmi_id" field.
func RmiIDGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldRmiID, v))
}

// RmiIDLT applies the LT predicate on the "rmi_id" field.
func RmiIDLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldRmiID, v))
}

// RmiIDLTE applies the LTE predicate on the "rmi_id" field.
func RmiIDLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldRmiID, v))
}

// RmiIDContains applies the Contains predicate on the "rmi_id" field.
func RmiIDContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldRmiID, v))
}

// RmiIDHasPrefix applies the HasPrefix predicate on the "rmi_id" field.
func RmiIDHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldRmiID, v))
}

// RmiIDHasSuffix applies the HasSuffix predicate on the "rmi_id" field.
func RmiIDHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldRmiID, v))
}

// RmiIDIsNil applies the IsNil predicate on the "rmi_id" field.
func RmiIDIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldRmiID))
}

// RmiIDNotNil applies the NotNil predicate on the "rmi_id" field.
func RmiIDNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldRmiID))
}

// RmiIDEqualFold applies the EqualFold predicate on the "rmi_id" field.
func RmiIDEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldRmiID, v))
}

// RmiIDContainsFold applies the ContainsFold predicate on the "rmi_id" field.
func RmiIDContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldRmiID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldTitle, v))
}

// CycleNumberEQ applies the EQ predicate on the "cycle_number" field.
func CycleNumberEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCycleNumber, v))
}

// CycleNumberNEQ applies the NEQ predicate on the "cycle_number" field.
func CycleNumberNEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldCycleNumber, v))
}

// CycleNumberIn applies the In predicate on the "cycle_number" field.
func CycleNumberIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldCycleNumber, vs...))
}

// CycleNumberNotIn applies the NotIn predicate on the "cycle_number" field.
func CycleNumberNotIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldCycleNumber, vs...))
}

// CycleNumberGT applies the GT predicate on the "cycle_number" field.
func CycleNumberGT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldCycleNumber, v))
}

// CycleNumberGTE applies the GTE predicate on the "cycle_number" field.
func CycleNumberGTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldCycleNumber, v))
}

// CycleNumberLT applies the LT predicate on the "cycle_number" field.
func CycleNumberLT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldCycleNumber, v))
}

// CycleNumberLTE applies the LTE predicate on the "cycle_number" field.
func CycleNumberLTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldCycleNumber, v))
}

// AssessedAtEQ applies the EQ predicate on the "assessed_at" field.
func AssessedAtEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldAssessedAt, v))
}

// AssessedAtNEQ applies the NEQ predicate on the "assessed_at" field.
func AssessedAtNEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldAssessedAt, v))
}

// AssessedAtIn applies the In predicate on the "assessed_at" field.
func AssessedAtIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldAssessedAt, vs...))
}

// AssessedAtNotIn applies the NotIn predicate on the "assessed_at" field.
func AssessedAtNotIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldAssessedAt, vs...))
}

// AssessedAtGT applies the GT predicate on the "assessed_at" field.
func AssessedAtGT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldAssessedAt, v))
}

// AssessedAtGTE applies the GTE predicate on the "assessed_at" field.
func AssessedAtGTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldAssessedAt, v))
}

// AssessedAtLT applies the LT predicate on the "assessed_at" field.
func AssessedAtLT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldAssessedAt, v))
}

// AssessedAtLTE applies the LTE predicate on the "assessed_at" field.
func AssessedAtLTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldAssessedAt, v))
}

// SupersedesIDEQ applies the EQ predicate on the "supersedes_id" field.
func SupersedesIDEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldSupersedesID, v))
}

// SupersedesIDNEQ applies the NEQ predicate on the "supersedes_id" field.
func SupersedesIDNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldSupersedesID, v))
}

// SupersedesIDIn applies the In predicate on the "supersedes_id" field.
func SupersedesIDIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldSupersedesID, vs...))
}

// SupersedesIDNotIn applies the NotIn predicate on the "supersedes_id" field.
func SupersedesIDNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldSupersedesID, vs...))
}

// SupersedesIDGT applies the GT predicate on the "supersedes_id" field.
func SupersedesIDGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldSupersedesID, v))
}

// SupersedesIDGTE applies the GTE predicate on the "supersedes_id" field.
func SupersedesIDGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldSupersedesID, v))
}

// SupersedesIDLT applies the LT predicate on the "supersedes_id" field.
func SupersedesIDLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldSupersedesID, v))
}

// SupersedesIDLTE applies the LTE predicate on the "supersedes_id" field.
func SupersedesIDLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldSupersedesID, v))
}

// SupersedesIDContains applies the Contains predicate on the "supersedes_id" field.
func SupersedesIDContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldSupersedesID, v))
}

// SupersedesIDHasPrefix applies the HasPrefix predicate on the "supersedes_id" field.
func SupersedesIDHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldSupersedesID, v))
}

// SupersedesIDHasSuffix applies the HasSuffix predicate on the "supersedes_id" field.
func SupersedesIDHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldSupersedesID, v))
}

// SupersedesIDIsNil applies the IsNil predicate on the "supersedes_id" field.
func SupersedesIDIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldSupersedesID))
}

// SupersedesIDNotNil applies the NotNil predicate on the "supersedes_id" field.
func SupersedesIDNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldSupersedesID))
}

// SupersedesIDEqualFold applies the EqualFold predicate on the "supersedes_id" field.
func SupersedesIDEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldSupersedesID, v))
}

// SupersedesIDContainsFold applies the ContainsFold predicate on the "supersedes_id" field.
func SupersedesIDContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldSupersedesID, v))
}

// CurrentEQ applies the EQ predicate on the "current" field.
func CurrentEQ(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCurrent, v))
}

// CurrentNEQ applies the NEQ predicate on the "current" field.
func CurrentNEQ(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldCurrent, v))
}

// MoscowClassEQ applies the EQ predicate on the "moscow_class" field.
func MoscowClassEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldMoscowClass, v))
}

// MoscowClassNEQ applies the NEQ predicate on the "moscow_class" field.
func MoscowClassNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldMoscowClass, v))
}

// MoscowClassIn applies the In predicate on the "moscow_class" field.
func MoscowClassIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldMoscowClass, vs...))
}

// MoscowClassNotIn applies the NotIn predicate on the "moscow_class" field.
func MoscowClassNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldMoscowClass, vs...))
}

// MoscowClassGT applies the GT predicate on the "moscow_class" field.
func MoscowClassGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldMoscowClass, v))
}

// MoscowClassGTE applies the GTE predicate on the "moscow_class" field.
func MoscowClassGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldMoscowClass, v))
}

// MoscowClassLT applies the LT predicate on the "moscow_class" field.
func MoscowClassLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldMoscowClass, v))
}

// MoscowClassLTE applies the LTE predicate on the "moscow_class" field.
func MoscowClassLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldMoscowClass, v))
}

// MoscowClassContains applies the Contains predicate on the "moscow_class" field.
func MoscowClassContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldMoscowClass, v))
}

// MoscowClassHasPrefix applies the HasPrefix predicate on the "moscow_class" field.
func MoscowClassHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldMoscowClass, v))
}

// MoscowClassHasSuffix applies the HasSuffix predicate on the "moscow_class" field.
func MoscowClassHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldMoscowClass, v))
}

// MoscowClassIsNil applies the IsNil predicate on the "moscow_class" field.
func MoscowClassIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldMoscowClass))
}

// MoscowClassNotNil applies the NotNil predicate on the "moscow_class" field.
func MoscowClassNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldMoscowClass))
}

// MoscowClassEqualFold applies the EqualFold predicate on the "moscow_class" field.
func MoscowClassEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldMoscowClass, v))
}

// MoscowClassContainsFold applies the ContainsFold predicate on the "moscow_class" field.
func MoscowClassContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldMoscowClass, v))
}

// RiceScoreEQ applies the EQ predicate on the "rice_score" field.
func RiceScoreEQ(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRiceScore, v))
}

// RiceScoreNEQ applies the NEQ predicate on the "rice_score" field.
func RiceScoreNEQ(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldRiceScore, v))
}

// RiceScoreIn applies the In predicate on the "rice_score" field.
func RiceScoreIn(vs ...float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldRiceScore, vs...))
}

// RiceScoreNotIn applies the NotIn predicate on the "rice_score" field.
func RiceScoreNotIn(vs ...float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldRiceScore, vs...))
}

// RiceScoreGT applies the GT predicate on the "rice_score" field.
func RiceScoreGT(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldRiceScore, v))
}

// RiceScoreGTE applies the GTE predicate on the "rice_score" field.
func RiceScoreGTE(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldRiceScore, v))
}

// RiceScoreLT applies the LT predicate on the "rice_score" field.
func RiceScoreLT(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldRiceScore, v))
}

// RiceScoreLTE applies the LTE predicate on the "rice_score" field.
func RiceScoreLTE(v float64) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldRiceScore, v))
}

// RiceScoreIsNil applies the IsNil predicate on the "rice_score" field.
func RiceScoreIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldRiceScore))
}

// RiceScoreNotNil applies the NotNil predicate on the "rice_score" field.
func RiceScoreNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldRiceScore))
}

// RiceComputableEQ applies the EQ predicate on the "rice_computable" field.
func RiceComputableEQ(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldRiceComputable, v))
}

// RiceComputableNEQ applies the NEQ predicate on the "rice_computable" field.
func RiceComputableNEQ(v bool) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldRiceComputable, v))
}

// OpportunityRankCalculatedEQ applies the EQ predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedNEQ applies the NEQ predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedNEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedIn applies the In predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldOpportunityRankCalculated, vs...))
}

// OpportunityRankCalculatedNotIn applies the NotIn predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedNotIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldOpportunityRankCalculated, vs...))
}

// OpportunityRankCalculatedGT applies the GT predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedGT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedGTE applies the GTE predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedGTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedLT applies the LT predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedLT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedLTE applies the LTE predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedLTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldOpportunityRankCalculated, v))
}

// OpportunityRankCalculatedIsNil applies the IsNil predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldOpportunityRankCalculated))
}

// OpportunityRankCalculatedNotNil applies the NotNil predicate on the "opportunity_rank_calculated" field.
func OpportunityRankCalculatedNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldOpportunityRankCalculated))
}

// OpportunityRankFinalEQ applies the EQ predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalNEQ applies the NEQ predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalNEQ(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalIn applies the In predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldOpportunityRankFinal, vs...))
}

// OpportunityRankFinalNotIn applies the NotIn predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalNotIn(vs ...int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldOpportunityRankFinal, vs...))
}

// OpportunityRankFinalGT applies the GT predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalGT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalGTE applies the GTE predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalGTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalLT applies the LT predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalLT(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalLTE applies the LTE predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalLTE(v int) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldOpportunityRankFinal, v))
}

// OpportunityRankFinalIsNil applies the IsNil predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldOpportunityRankFinal))
}

// OpportunityRankFinalNotNil applies the NotNil predicate on the "opportunity_rank_final" field.
func OpportunityRankFinalNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldOpportunityRankFinal))
}

// KanoCategoryEQ applies the EQ predicate on the "kano_category" field.
func KanoCategoryEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldKanoCategory, v))
}

// KanoCategoryNEQ applies the NEQ predicate on the "kano_category" field.
func KanoCategoryNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldKanoCategory, v))
}

// KanoCategoryIn applies the In predicate on the "kano_category" field.
func KanoCategoryIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldKanoCategory, vs...))
}

// KanoCategoryNotIn applies the NotIn predicate on the "kano_category" field.
func KanoCategoryNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldKanoCategory, vs...))
}

// KanoCategoryGT applies the GT predicate on the "kano_category" field.
func KanoCategoryGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldKanoCategory, v))
}

// KanoCategoryGTE applies the GTE predicate on the "kano_category" field.
func KanoCategoryGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldKanoCategory, v))
}

// KanoCategoryLT applies the LT predicate on the "kano_category" field.
func KanoCategoryLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldKanoCategory, v))
}

// KanoCategoryLTE applies the LTE predicate on the "kano_category" field.
func KanoCategoryLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldKanoCategory, v))
}

// KanoCategoryContains applies the Contains predicate on the "kano_category" field.
func KanoCategoryContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldKanoCategory, v))
}

// KanoCategoryHasPrefix applies the HasPrefix predicate on the "kano_category" field.
func KanoCategoryHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldKanoCategory, v))
}

// KanoCategoryHasSuffix applies the HasSuffix predicate on the "kano_category" field.
func KanoCategoryHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldKanoCategory, v))
}

// KanoCategoryIsNil applies the IsNil predicate on the "kano_category" field.
func KanoCategoryIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldKanoCategory))
}

// KanoCategoryNotNil applies the NotNil predicate on the "kano_category" field.
func KanoCategoryNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldKanoCategory))
}

// KanoCategoryEqualFold applies the EqualFold predicate on the "kano_category" field.
func KanoCategoryEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldKanoCategory, v))
}

// KanoCategoryContainsFold applies the ContainsFold predicate on the "kano_category" field.
func KanoCategoryContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldKanoCategory, v))
}

// MihCategoryEQ applies the EQ predicate on the "mih_category" field.
func MihCategoryEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldMihCategory, v))
}

// MihCategoryNEQ applies the NEQ predicate on the "mih_category" field.
func MihCategoryNEQ(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldMihCategory, v))
}

// MihCategoryIn applies the In predicate on the "mih_category" field.
func MihCategoryIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldMihCategory, vs...))
}

// MihCategoryNotIn applies the NotIn predicate on the "mih_category" field.
func MihCategoryNotIn(vs ...string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldMihCategory, vs...))
}

// MihCategoryGT applies the GT predicate on the "mih_category" field.
func MihCategoryGT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldMihCategory, v))
}

// MihCategoryGTE applies the GTE predicate on the "mih_category" field.
func MihCategoryGTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldMihCategory, v))
}

// MihCategoryLT applies the LT predicate on the "mih_category" field.
func MihCategoryLT(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldMihCategory, v))
}

// MihCategoryLTE applies the LTE predicate on the "mih_category" field.
func MihCategoryLTE(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldMihCategory, v))
}

// MihCategoryContains applies the Contains predicate on the "mih_category" field.
func MihCategoryContains(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContains(FieldMihCategory, v))
}

// MihCategoryHasPrefix applies the HasPrefix predicate on the "mih_category" field.
func MihCategoryHasPrefix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasPrefix(FieldMihCategory, v))
}

// MihCategoryHasSuffix applies the HasSuffix predicate on the "mih_category" field.
func MihCategoryHasSuffix(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldHasSuffix(FieldMihCategory, v))
}

// MihCategoryIsNil applies the IsNil predicate on the "mih_category" field.
func MihCategoryIsNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIsNull(FieldMihCategory))
}

// MihCategoryNotNil applies the NotNil predicate on the "mih_category" field.
func MihCategoryNotNil() predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotNull(FieldMihCategory))
}

// MihCategoryEqualFold applies the EqualFold predicate on the "mih_category" field.
func MihCategoryEqualFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEqualFold(FieldMihCategory, v))
}

// MihCategoryContainsFold applies the ContainsFold predicate on the "mih_category" field.
func MihCategoryContainsFold(v string) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldContainsFold(FieldMihCategory, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpportunityAssessment) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpportunityAssessment) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpportunityAssessment) predicate.OpportunityAssessment {
	return predicate.OpportunityAssessment(sql.NotPredicates(p))
}
