// Code generated by ent, DO NOT EDIT.

package rankoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rankoverride type in the database.
	Label = "rank_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFinalRank holds the string denoting the final_rank field in the database.
	FieldFinalRank = "final_rank"
	// FieldRationale holds the string denoting the rationale field in the database.
	FieldRationale = "rationale"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldEvidenceIds holds the string denoting the evidence_ids field in the database.
	FieldEvidenceIds = "evidence_ids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the rankoverride in the database.
	Table = "rank_overrides"
)

// Columns holds all SQL columns for rankoverride fields.
var Columns = []string{
	FieldID,
	FieldFinalRank,
	FieldRationale,
	FieldApprovedBy,
	FieldEvidenceIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RationaleValidator is a validator for the "rationale" field. It is called by the builders before save.
	RationaleValidator func(string) error
	// ApprovedByValidator is a validator for the "approved_by" field. It is called by the builders before save.
	ApprovedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the RankOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFinalRank orders the results by the final_rank field.
func ByFinalRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalRank, opts...).ToFunc()
}

// ByRationale orders the results by the rationale field.
func ByRationale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRationale, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
