// Code generated by ent, DO NOT EDIT.

package portfoliodimension

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContainsFold(FieldID, id))
}

// DimensionID applies equality check predicate on the "dimension_id" field. It's identical to DimensionIDEQ.
func DimensionID(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldDimensionID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldVersion, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldName, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldKind, v))
}

// BuiltIn applies equality check predicate on the "built_in" field. It's identical to BuiltInEQ.
func BuiltIn(v bool) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldBuiltIn, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldCreatedAt, v))
}

// DimensionIDEQ applies the EQ predicate on the "dimension_id" field.
func DimensionIDEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldDimensionID, v))
}

// DimensionIDNEQ applies the NEQ predicate on the "dimension_id" field.
func DimensionIDNEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldDimensionID, v))
}

// DimensionIDIn applies the In predicate on the "dimension_id" field.
func DimensionIDIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldDimensionID, vs...))
}

// DimensionIDNotIn applies the NotIn predicate on the "dimension_id" field.
func DimensionIDNotIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldDimensionID, vs...))
}

// DimensionIDGT applies the GT predicate on the "dimension_id" field.
func DimensionIDGT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldDimensionID, v))
}

// DimensionIDGTE applies the GTE predicate on the "dimension_id" field.
func DimensionIDGTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldDimensionID, v))
}

// DimensionIDLT applies the LT predicate on the "dimension_id" field.
func DimensionIDLT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldDimensionID, v))
}

// DimensionIDLTE applies the LTE predicate on the "dimension_id" field.
func DimensionIDLTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldDimensionID, v))
}

// DimensionIDContains applies the Contains predicate on the "dimension_id" field.
func DimensionIDContains(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContains(FieldDimensionID, v))
}

// DimensionIDHasPrefix applies the HasPrefix predicate on the "dimension_id" field.
func DimensionIDHasPrefix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasPrefix(FieldDimensionID, v))
}

// DimensionIDHasSuffix applies the HasSuffix predicate on the "dimension_id" field.
func DimensionIDHasSuffix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasSuffix(FieldDimensionID, v))
}

// DimensionIDEqualFold applies the EqualFold predicate on the "dimension_id" field.
func DimensionIDEqualFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEqualFold(FieldDimensionID, v))
}

// DimensionIDContainsFold applies the ContainsFold predicate on the "dimension_id" field.
func DimensionIDContainsFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContainsFold(FieldDimensionID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContainsFold(FieldVersion, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldContainsFold(FieldKind, v))
}

// BuiltInEQ applies the EQ predicate on the "built_in" field.
func BuiltInEQ(v bool) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldBuiltIn, v))
}

// BuiltInNEQ applies the NEQ predicate on the "built_in" field.
func BuiltInNEQ(v bool) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldBuiltIn, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PortfolioDimension) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PortfolioDimension) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PortfolioDimension) predicate.PortfolioDimension {
	return predicate.PortfolioDimension(sql.NotPredicates(p))
}
