// Code generated by ent, DO NOT EDIT.

package profileassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the profileassignment type in the database.
	Label = "profile_assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProfileID holds the string denoting the profile_id field in the database.
	FieldProfileID = "profile_id"
	// FieldSecondary holds the string denoting the secondary field in the database.
	FieldSecondary = "secondary"
	// FieldRationale holds the string denoting the rationale field in the database.
	FieldRationale = "rationale"
	// FieldProposedBy holds the string denoting the proposed_by field in the database.
	FieldProposedBy = "proposed_by"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConfirmedBy holds the string denoting the confirmed_by field in the database.
	FieldConfirmedBy = "confirmed_by"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldEvidenceIds holds the string denoting the evidence_ids field in the database.
	FieldEvidenceIds = "evidence_ids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the profileassignment in the database.
	Table = "profile_assignments"
)

// Columns holds all SQL columns for profileassignment fields.
var Columns = []string{
	FieldID,
	FieldProfileID,
	FieldSecondary,
	FieldRationale,
	FieldProposedBy,
	FieldStatus,
	FieldConfirmedBy,
	FieldConfirmedAt,
	FieldEvidenceIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProfileIDValidator is a validator for the "profile_id" field. It is called by the builders before save.
	ProfileIDValidator func(string) error
	// RationaleValidator is a validator for the "rationale" field. It is called by the builders before save.
	RationaleValidator func(string) error
	// ProposedByValidator is a validator for the "proposed_by" field. It is called by the builders before save.
	ProposedByValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ConfirmedByValidator is a validator for the "confirmed_by" field. It is called by the builders before save.
	ConfirmedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ProfileAssignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProfileID orders the results by the profile_id field.
func ByProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileID, opts...).ToFunc()
}

// ByRationale orders the results by the rationale field.
func ByRationale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRationale, opts...).ToFunc()
}

// ByProposedBy orders the results by the proposed_by field.
func ByProposedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProposedBy, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConfirmedBy orders the results by the confirmed_by field.
func ByConfirmedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedBy, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
