// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/grokify/omniroadmap/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/customfielddef"
	"github.com/grokify/omniroadmap/ent/dimensionoption"
	"github.com/grokify/omniroadmap/ent/evidence"
	"github.com/grokify/omniroadmap/ent/item"
	"github.com/grokify/omniroadmap/ent/itemaugment"
	"github.com/grokify/omniroadmap/ent/opportunityassessment"
	"github.com/grokify/omniroadmap/ent/opportunityspec"
	"github.com/grokify/omniroadmap/ent/portfoliodimension"
	"github.com/grokify/omniroadmap/ent/rankoverride"
	"github.com/grokify/omniroadmap/ent/release"
	"github.com/grokify/omniroadmap/ent/reportdataset"
	"github.com/grokify/omniroadmap/ent/syncmeta"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CustomFieldDef is the client for interacting with the CustomFieldDef builders.
	CustomFieldDef *CustomFieldDefClient
	// DimensionOption is the client for interacting with the DimensionOption builders.
	DimensionOption *DimensionOptionClient
	// Evidence is the client for interacting with the Evidence builders.
	Evidence *EvidenceClient
	// Item is the client for interacting with the Item builders.
	Item *ItemClient
	// ItemAugment is the client for interacting with the ItemAugment builders.
	ItemAugment *ItemAugmentClient
	// OpportunityAssessment is the client for interacting with the OpportunityAssessment builders.
	OpportunityAssessment *OpportunityAssessmentClient
	// OpportunitySpec is the client for interacting with the OpportunitySpec builders.
	OpportunitySpec *OpportunitySpecClient
	// PortfolioDimension is the client for interacting with the PortfolioDimension builders.
	PortfolioDimension *PortfolioDimensionClient
	// RankOverride is the client for interacting with the RankOverride builders.
	RankOverride *RankOverrideClient
	// Release is the client for interacting with the Release builders.
	Release *ReleaseClient
	// ReportDataset is the client for interacting with the ReportDataset builders.
	ReportDataset *ReportDatasetClient
	// SyncMeta is the client for interacting with the SyncMeta builders.
	SyncMeta *SyncMetaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CustomFieldDef = NewCustomFieldDefClient(c.config)
	c.DimensionOption = NewDimensionOptionClient(c.config)
	c.Evidence = NewEvidenceClient(c.config)
	c.Item = NewItemClient(c.config)
	c.ItemAugment = NewItemAugmentClient(c.config)
	c.OpportunityAssessment = NewOpportunityAssessmentClient(c.config)
	c.OpportunitySpec = NewOpportunitySpecClient(c.config)
	c.PortfolioDimension = NewPortfolioDimensionClient(c.config)
	c.RankOverride = NewRankOverrideClient(c.config)
	c.Release = NewReleaseClient(c.config)
	c.ReportDataset = NewReportDatasetClient(c.config)
	c.SyncMeta = NewSyncMetaClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		CustomFieldDef:        NewCustomFieldDefClient(cfg),
		DimensionOption:       NewDimensionOptionClient(cfg),
		Evidence:              NewEvidenceClient(cfg),
		Item:                  NewItemClient(cfg),
		ItemAugment:           NewItemAugmentClient(cfg),
		OpportunityAssessment: NewOpportunityAssessmentClient(cfg),
		OpportunitySpec:       NewOpportunitySpecClient(cfg),
		PortfolioDimension:    NewPortfolioDimensionClient(cfg),
		RankOverride:          NewRankOverrideClient(cfg),
		Release:               NewReleaseClient(cfg),
		ReportDataset:         NewReportDatasetClient(cfg),
		SyncMeta:              NewSyncMetaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		CustomFieldDef:        NewCustomFieldDefClient(cfg),
		DimensionOption:       NewDimensionOptionClient(cfg),
		Evidence:              NewEvidenceClient(cfg),
		Item:                  NewItemClient(cfg),
		ItemAugment:           NewItemAugmentClient(cfg),
		OpportunityAssessment: NewOpportunityAssessmentClient(cfg),
		OpportunitySpec:       NewOpportunitySpecClient(cfg),
		PortfolioDimension:    NewPortfolioDimensionClient(cfg),
		RankOverride:          NewRankOverrideClient(cfg),
		Release:               NewReleaseClient(cfg),
		ReportDataset:         NewReportDatasetClient(cfg),
		SyncMeta:              NewSyncMetaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CustomFieldDef.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CustomFieldDef, c.DimensionOption, c.Evidence, c.Item, c.ItemAugment,
		c.OpportunityAssessment, c.OpportunitySpec, c.PortfolioDimension,
		c.RankOverride, c.Release, c.ReportDataset, c.SyncMeta,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CustomFieldDef, c.DimensionOption, c.Evidence, c.Item, c.ItemAugment,
		c.OpportunityAssessment, c.OpportunitySpec, c.PortfolioDimension,
		c.RankOverride, c.Release, c.ReportDataset, c.SyncMeta,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CustomFieldDefMutation:
		return c.CustomFieldDef.mutate(ctx, m)
	case *DimensionOptionMutation:
		return c.DimensionOption.mutate(ctx, m)
	case *EvidenceMutation:
		return c.Evidence.mutate(ctx, m)
	case *ItemMutation:
		return c.Item.mutate(ctx, m)
	case *ItemAugmentMutation:
		return c.ItemAugment.mutate(ctx, m)
	case *OpportunityAssessmentMutation:
		return c.OpportunityAssessment.mutate(ctx, m)
	case *OpportunitySpecMutation:
		return c.OpportunitySpec.mutate(ctx, m)
	case *PortfolioDimensionMutation:
		return c.PortfolioDimension.mutate(ctx, m)
	case *RankOverrideMutation:
		return c.RankOverride.mutate(ctx, m)
	case *ReleaseMutation:
		return c.Release.mutate(ctx, m)
	case *ReportDatasetMutation:
		return c.ReportDataset.mutate(ctx, m)
	case *SyncMetaMutation:
		return c.SyncMeta.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CustomFieldDefClient is a client for the CustomFieldDef schema.
type CustomFieldDefClient struct {
	config
}

// NewCustomFieldDefClient returns a client for the CustomFieldDef from the given config.
func NewCustomFieldDefClient(c config) *CustomFieldDefClient {
	return &CustomFieldDefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customfielddef.Hooks(f(g(h())))`.
func (c *CustomFieldDefClient) Use(hooks ...Hook) {
	c.hooks.CustomFieldDef = append(c.hooks.CustomFieldDef, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customfielddef.Intercept(f(g(h())))`.
func (c *CustomFieldDefClient) Intercept(interceptors ...Interceptor) {
	c.inters.CustomFieldDef = append(c.inters.CustomFieldDef, interceptors...)
}

// Create returns a builder for creating a CustomFieldDef entity.
func (c *CustomFieldDefClient) Create() *CustomFieldDefCreate {
	mutation := newCustomFieldDefMutation(c.config, OpCreate)
	return &CustomFieldDefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomFieldDef entities.
func (c *CustomFieldDefClient) CreateBulk(builders ...*CustomFieldDefCreate) *CustomFieldDefCreateBulk {
	return &CustomFieldDefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomFieldDefClient) MapCreateBulk(slice any, setFunc func(*CustomFieldDefCreate, int)) *CustomFieldDefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomFieldDefCreateBulk{err: fmt.Errorf("calling to CustomFieldDefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomFieldDefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomFieldDefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomFieldDef.
func (c *CustomFieldDefClient) Update() *CustomFieldDefUpdate {
	mutation := newCustomFieldDefMutation(c.config, OpUpdate)
	return &CustomFieldDefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomFieldDefClient) UpdateOne(_m *CustomFieldDef) *CustomFieldDefUpdateOne {
	mutation := newCustomFieldDefMutation(c.config, OpUpdateOne, withCustomFieldDef(_m))
	return &CustomFieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomFieldDefClient) UpdateOneID(id string) *CustomFieldDefUpdateOne {
	mutation := newCustomFieldDefMutation(c.config, OpUpdateOne, withCustomFieldDefID(id))
	return &CustomFieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomFieldDef.
func (c *CustomFieldDefClient) Delete() *CustomFieldDefDelete {
	mutation := newCustomFieldDefMutation(c.config, OpDelete)
	return &CustomFieldDefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomFieldDefClient) DeleteOne(_m *CustomFieldDef) *CustomFieldDefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomFieldDefClient) DeleteOneID(id string) *CustomFieldDefDeleteOne {
	builder := c.Delete().Where(customfielddef.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomFieldDefDeleteOne{builder}
}

// Query returns a query builder for CustomFieldDef.
func (c *CustomFieldDefClient) Query() *CustomFieldDefQuery {
	return &CustomFieldDefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomFieldDef},
		inters: c.Interceptors(),
	}
}

// Get returns a CustomFieldDef entity by its id.
func (c *CustomFieldDefClient) Get(ctx context.Context, id string) (*CustomFieldDef, error) {
	return c.Query().Where(customfielddef.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomFieldDefClient) GetX(ctx context.Context, id string) *CustomFieldDef {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CustomFieldDefClient) Hooks() []Hook {
	return c.hooks.CustomFieldDef
}

// Interceptors returns the client interceptors.
func (c *CustomFieldDefClient) Interceptors() []Interceptor {
	return c.inters.CustomFieldDef
}

func (c *CustomFieldDefClient) mutate(ctx context.Context, m *CustomFieldDefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomFieldDefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomFieldDefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomFieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomFieldDefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CustomFieldDef mutation op: %q", m.Op())
	}
}

// DimensionOptionClient is a client for the DimensionOption schema.
type DimensionOptionClient struct {
	config
}

// NewDimensionOptionClient returns a client for the DimensionOption from the given config.
func NewDimensionOptionClient(c config) *DimensionOptionClient {
	return &DimensionOptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dimensionoption.Hooks(f(g(h())))`.
func (c *DimensionOptionClient) Use(hooks ...Hook) {
	c.hooks.DimensionOption = append(c.hooks.DimensionOption, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dimensionoption.Intercept(f(g(h())))`.
func (c *DimensionOptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.DimensionOption = append(c.inters.DimensionOption, interceptors...)
}

// Create returns a builder for creating a DimensionOption entity.
func (c *DimensionOptionClient) Create() *DimensionOptionCreate {
	mutation := newDimensionOptionMutation(c.config, OpCreate)
	return &DimensionOptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DimensionOption entities.
func (c *DimensionOptionClient) CreateBulk(builders ...*DimensionOptionCreate) *DimensionOptionCreateBulk {
	return &DimensionOptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DimensionOptionClient) MapCreateBulk(slice any, setFunc func(*DimensionOptionCreate, int)) *DimensionOptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DimensionOptionCreateBulk{err: fmt.Errorf("calling to DimensionOptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DimensionOptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DimensionOptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DimensionOption.
func (c *DimensionOptionClient) Update() *DimensionOptionUpdate {
	mutation := newDimensionOptionMutation(c.config, OpUpdate)
	return &DimensionOptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DimensionOptionClient) UpdateOne(_m *DimensionOption) *DimensionOptionUpdateOne {
	mutation := newDimensionOptionMutation(c.config, OpUpdateOne, withDimensionOption(_m))
	return &DimensionOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DimensionOptionClient) UpdateOneID(id string) *DimensionOptionUpdateOne {
	mutation := newDimensionOptionMutation(c.config, OpUpdateOne, withDimensionOptionID(id))
	return &DimensionOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DimensionOption.
func (c *DimensionOptionClient) Delete() *DimensionOptionDelete {
	mutation := newDimensionOptionMutation(c.config, OpDelete)
	return &DimensionOptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DimensionOptionClient) DeleteOne(_m *DimensionOption) *DimensionOptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DimensionOptionClient) DeleteOneID(id string) *DimensionOptionDeleteOne {
	builder := c.Delete().Where(dimensionoption.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DimensionOptionDeleteOne{builder}
}

// Query returns a query builder for DimensionOption.
func (c *DimensionOptionClient) Query() *DimensionOptionQuery {
	return &DimensionOptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDimensionOption},
		inters: c.Interceptors(),
	}
}

// Get returns a DimensionOption entity by its id.
func (c *DimensionOptionClient) Get(ctx context.Context, id string) (*DimensionOption, error) {
	return c.Query().Where(dimensionoption.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DimensionOptionClient) GetX(ctx context.Context, id string) *DimensionOption {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DimensionOptionClient) Hooks() []Hook {
	return c.hooks.DimensionOption
}

// Interceptors returns the client interceptors.
func (c *DimensionOptionClient) Interceptors() []Interceptor {
	return c.inters.DimensionOption
}

func (c *DimensionOptionClient) mutate(ctx context.Context, m *DimensionOptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DimensionOptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DimensionOptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DimensionOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DimensionOptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DimensionOption mutation op: %q", m.Op())
	}
}

// EvidenceClient is a client for the Evidence schema.
type EvidenceClient struct {
	config
}

// NewEvidenceClient returns a client for the Evidence from the given config.
func NewEvidenceClient(c config) *EvidenceClient {
	return &EvidenceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `evidence.Hooks(f(g(h())))`.
func (c *EvidenceClient) Use(hooks ...Hook) {
	c.hooks.Evidence = append(c.hooks.Evidence, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `evidence.Intercept(f(g(h())))`.
func (c *EvidenceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Evidence = append(c.inters.Evidence, interceptors...)
}

// Create returns a builder for creating a Evidence entity.
func (c *EvidenceClient) Create() *EvidenceCreate {
	mutation := newEvidenceMutation(c.config, OpCreate)
	return &EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Evidence entities.
func (c *EvidenceClient) CreateBulk(builders ...*EvidenceCreate) *EvidenceCreateBulk {
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EvidenceClient) MapCreateBulk(slice any, setFunc func(*EvidenceCreate, int)) *EvidenceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EvidenceCreateBulk{err: fmt.Errorf("calling to EvidenceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EvidenceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Evidence.
func (c *EvidenceClient) Update() *EvidenceUpdate {
	mutation := newEvidenceMutation(c.config, OpUpdate)
	return &EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EvidenceClient) UpdateOne(_m *Evidence) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidence(_m))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EvidenceClient) UpdateOneID(id string) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidenceID(id))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Evidence.
func (c *EvidenceClient) Delete() *EvidenceDelete {
	mutation := newEvidenceMutation(c.config, OpDelete)
	return &EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EvidenceClient) DeleteOne(_m *Evidence) *EvidenceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EvidenceClient) DeleteOneID(id string) *EvidenceDeleteOne {
	builder := c.Delete().Where(evidence.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EvidenceDeleteOne{builder}
}

// Query returns a query builder for Evidence.
func (c *EvidenceClient) Query() *EvidenceQuery {
	return &EvidenceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvidence},
		inters: c.Interceptors(),
	}
}

// Get returns a Evidence entity by its id.
func (c *EvidenceClient) Get(ctx context.Context, id string) (*Evidence, error) {
	return c.Query().Where(evidence.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EvidenceClient) GetX(ctx context.Context, id string) *Evidence {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EvidenceClient) Hooks() []Hook {
	return c.hooks.Evidence
}

// Interceptors returns the client interceptors.
func (c *EvidenceClient) Interceptors() []Interceptor {
	return c.inters.Evidence
}

func (c *EvidenceClient) mutate(ctx context.Context, m *EvidenceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Evidence mutation op: %q", m.Op())
	}
}

// ItemClient is a client for the Item schema.
type ItemClient struct {
	config
}

// NewItemClient returns a client for the Item from the given config.
func NewItemClient(c config) *ItemClient {
	return &ItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `item.Hooks(f(g(h())))`.
func (c *ItemClient) Use(hooks ...Hook) {
	c.hooks.Item = append(c.hooks.Item, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `item.Intercept(f(g(h())))`.
func (c *ItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.Item = append(c.inters.Item, interceptors...)
}

// Create returns a builder for creating a Item entity.
func (c *ItemClient) Create() *ItemCreate {
	mutation := newItemMutation(c.config, OpCreate)
	return &ItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Item entities.
func (c *ItemClient) CreateBulk(builders ...*ItemCreate) *ItemCreateBulk {
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ItemClient) MapCreateBulk(slice any, setFunc func(*ItemCreate, int)) *ItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ItemCreateBulk{err: fmt.Errorf("calling to ItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Item.
func (c *ItemClient) Update() *ItemUpdate {
	mutation := newItemMutation(c.config, OpUpdate)
	return &ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemClient) UpdateOne(_m *Item) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItem(_m))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemClient) UpdateOneID(id string) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItemID(id))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Item.
func (c *ItemClient) Delete() *ItemDelete {
	mutation := newItemMutation(c.config, OpDelete)
	return &ItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ItemClient) DeleteOne(_m *Item) *ItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ItemClient) DeleteOneID(id string) *ItemDeleteOne {
	builder := c.Delete().Where(item.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemDeleteOne{builder}
}

// Query returns a query builder for Item.
func (c *ItemClient) Query() *ItemQuery {
	return &ItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeItem},
		inters: c.Interceptors(),
	}
}

// Get returns a Item entity by its id.
func (c *ItemClient) Get(ctx context.Context, id string) (*Item, error) {
	return c.Query().Where(item.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemClient) GetX(ctx context.Context, id string) *Item {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ItemClient) Hooks() []Hook {
	return c.hooks.Item
}

// Interceptors returns the client interceptors.
func (c *ItemClient) Interceptors() []Interceptor {
	return c.inters.Item
}

func (c *ItemClient) mutate(ctx context.Context, m *ItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Item mutation op: %q", m.Op())
	}
}

// ItemAugmentClient is a client for the ItemAugment schema.
type ItemAugmentClient struct {
	config
}

// NewItemAugmentClient returns a client for the ItemAugment from the given config.
func NewItemAugmentClient(c config) *ItemAugmentClient {
	return &ItemAugmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `itemaugment.Hooks(f(g(h())))`.
func (c *ItemAugmentClient) Use(hooks ...Hook) {
	c.hooks.ItemAugment = append(c.hooks.ItemAugment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `itemaugment.Intercept(f(g(h())))`.
func (c *ItemAugmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.ItemAugment = append(c.inters.ItemAugment, interceptors...)
}

// Create returns a builder for creating a ItemAugment entity.
func (c *ItemAugmentClient) Create() *ItemAugmentCreate {
	mutation := newItemAugmentMutation(c.config, OpCreate)
	return &ItemAugmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ItemAugment entities.
func (c *ItemAugmentClient) CreateBulk(builders ...*ItemAugmentCreate) *ItemAugmentCreateBulk {
	return &ItemAugmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ItemAugmentClient) MapCreateBulk(slice any, setFunc func(*ItemAugmentCreate, int)) *ItemAugmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ItemAugmentCreateBulk{err: fmt.Errorf("calling to ItemAugmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ItemAugmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ItemAugmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ItemAugment.
func (c *ItemAugmentClient) Update() *ItemAugmentUpdate {
	mutation := newItemAugmentMutation(c.config, OpUpdate)
	return &ItemAugmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemAugmentClient) UpdateOne(_m *ItemAugment) *ItemAugmentUpdateOne {
	mutation := newItemAugmentMutation(c.config, OpUpdateOne, withItemAugment(_m))
	return &ItemAugmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemAugmentClient) UpdateOneID(id string) *ItemAugmentUpdateOne {
	mutation := newItemAugmentMutation(c.config, OpUpdateOne, withItemAugmentID(id))
	return &ItemAugmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ItemAugment.
func (c *ItemAugmentClient) Delete() *ItemAugmentDelete {
	mutation := newItemAugmentMutation(c.config, OpDelete)
	return &ItemAugmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ItemAugmentClient) DeleteOne(_m *ItemAugment) *ItemAugmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ItemAugmentClient) DeleteOneID(id string) *ItemAugmentDeleteOne {
	builder := c.Delete().Where(itemaugment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemAugmentDeleteOne{builder}
}

// Query returns a query builder for ItemAugment.
func (c *ItemAugmentClient) Query() *ItemAugmentQuery {
	return &ItemAugmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeItemAugment},
		inters: c.Interceptors(),
	}
}

// Get returns a ItemAugment entity by its id.
func (c *ItemAugmentClient) Get(ctx context.Context, id string) (*ItemAugment, error) {
	return c.Query().Where(itemaugment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemAugmentClient) GetX(ctx context.Context, id string) *ItemAugment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ItemAugmentClient) Hooks() []Hook {
	return c.hooks.ItemAugment
}

// Interceptors returns the client interceptors.
func (c *ItemAugmentClient) Interceptors() []Interceptor {
	return c.inters.ItemAugment
}

func (c *ItemAugmentClient) mutate(ctx context.Context, m *ItemAugmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ItemAugmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ItemAugmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ItemAugmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ItemAugmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ItemAugment mutation op: %q", m.Op())
	}
}

// OpportunityAssessmentClient is a client for the OpportunityAssessment schema.
type OpportunityAssessmentClient struct {
	config
}

// NewOpportunityAssessmentClient returns a client for the OpportunityAssessment from the given config.
func NewOpportunityAssessmentClient(c config) *OpportunityAssessmentClient {
	return &OpportunityAssessmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `opportunityassessment.Hooks(f(g(h())))`.
func (c *OpportunityAssessmentClient) Use(hooks ...Hook) {
	c.hooks.OpportunityAssessment = append(c.hooks.OpportunityAssessment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `opportunityassessment.Intercept(f(g(h())))`.
func (c *OpportunityAssessmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.OpportunityAssessment = append(c.inters.OpportunityAssessment, interceptors...)
}

// Create returns a builder for creating a OpportunityAssessment entity.
func (c *OpportunityAssessmentClient) Create() *OpportunityAssessmentCreate {
	mutation := newOpportunityAssessmentMutation(c.config, OpCreate)
	return &OpportunityAssessmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OpportunityAssessment entities.
func (c *OpportunityAssessmentClient) CreateBulk(builders ...*OpportunityAssessmentCreate) *OpportunityAssessmentCreateBulk {
	return &OpportunityAssessmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OpportunityAssessmentClient) MapCreateBulk(slice any, setFunc func(*OpportunityAssessmentCreate, int)) *OpportunityAssessmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OpportunityAssessmentCreateBulk{err: fmt.Errorf("calling to OpportunityAssessmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OpportunityAssessmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OpportunityAssessmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OpportunityAssessment.
func (c *OpportunityAssessmentClient) Update() *OpportunityAssessmentUpdate {
	mutation := newOpportunityAssessmentMutation(c.config, OpUpdate)
	return &OpportunityAssessmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OpportunityAssessmentClient) UpdateOne(_m *OpportunityAssessment) *OpportunityAssessmentUpdateOne {
	mutation := newOpportunityAssessmentMutation(c.config, OpUpdateOne, withOpportunityAssessment(_m))
	return &OpportunityAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OpportunityAssessmentClient) UpdateOneID(id string) *OpportunityAssessmentUpdateOne {
	mutation := newOpportunityAssessmentMutation(c.config, OpUpdateOne, withOpportunityAssessmentID(id))
	return &OpportunityAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OpportunityAssessment.
func (c *OpportunityAssessmentClient) Delete() *OpportunityAssessmentDelete {
	mutation := newOpportunityAssessmentMutation(c.config, OpDelete)
	return &OpportunityAssessmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OpportunityAssessmentClient) DeleteOne(_m *OpportunityAssessment) *OpportunityAssessmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OpportunityAssessmentClient) DeleteOneID(id string) *OpportunityAssessmentDeleteOne {
	builder := c.Delete().Where(opportunityassessment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OpportunityAssessmentDeleteOne{builder}
}

// Query returns a query builder for OpportunityAssessment.
func (c *OpportunityAssessmentClient) Query() *OpportunityAssessmentQuery {
	return &OpportunityAssessmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOpportunityAssessment},
		inters: c.Interceptors(),
	}
}

// Get returns a OpportunityAssessment entity by its id.
func (c *OpportunityAssessmentClient) Get(ctx context.Context, id string) (*OpportunityAssessment, error) {
	return c.Query().Where(opportunityassessment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OpportunityAssessmentClient) GetX(ctx context.Context, id string) *OpportunityAssessment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OpportunityAssessmentClient) Hooks() []Hook {
	return c.hooks.OpportunityAssessment
}

// Interceptors returns the client interceptors.
func (c *OpportunityAssessmentClient) Interceptors() []Interceptor {
	return c.inters.OpportunityAssessment
}

func (c *OpportunityAssessmentClient) mutate(ctx context.Context, m *OpportunityAssessmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OpportunityAssessmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OpportunityAssessmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OpportunityAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OpportunityAssessmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OpportunityAssessment mutation op: %q", m.Op())
	}
}

// OpportunitySpecClient is a client for the OpportunitySpec schema.
type OpportunitySpecClient struct {
	config
}

// NewOpportunitySpecClient returns a client for the OpportunitySpec from the given config.
func NewOpportunitySpecClient(c config) *OpportunitySpecClient {
	return &OpportunitySpecClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `opportunityspec.Hooks(f(g(h())))`.
func (c *OpportunitySpecClient) Use(hooks ...Hook) {
	c.hooks.OpportunitySpec = append(c.hooks.OpportunitySpec, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `opportunityspec.Intercept(f(g(h())))`.
func (c *OpportunitySpecClient) Intercept(interceptors ...Interceptor) {
	c.inters.OpportunitySpec = append(c.inters.OpportunitySpec, interceptors...)
}

// Create returns a builder for creating a OpportunitySpec entity.
func (c *OpportunitySpecClient) Create() *OpportunitySpecCreate {
	mutation := newOpportunitySpecMutation(c.config, OpCreate)
	return &OpportunitySpecCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OpportunitySpec entities.
func (c *OpportunitySpecClient) CreateBulk(builders ...*OpportunitySpecCreate) *OpportunitySpecCreateBulk {
	return &OpportunitySpecCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OpportunitySpecClient) MapCreateBulk(slice any, setFunc func(*OpportunitySpecCreate, int)) *OpportunitySpecCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OpportunitySpecCreateBulk{err: fmt.Errorf("calling to OpportunitySpecClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OpportunitySpecCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OpportunitySpecCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OpportunitySpec.
func (c *OpportunitySpecClient) Update() *OpportunitySpecUpdate {
	mutation := newOpportunitySpecMutation(c.config, OpUpdate)
	return &OpportunitySpecUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OpportunitySpecClient) UpdateOne(_m *OpportunitySpec) *OpportunitySpecUpdateOne {
	mutation := newOpportunitySpecMutation(c.config, OpUpdateOne, withOpportunitySpec(_m))
	return &OpportunitySpecUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OpportunitySpecClient) UpdateOneID(id string) *OpportunitySpecUpdateOne {
	mutation := newOpportunitySpecMutation(c.config, OpUpdateOne, withOpportunitySpecID(id))
	return &OpportunitySpecUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OpportunitySpec.
func (c *OpportunitySpecClient) Delete() *OpportunitySpecDelete {
	mutation := newOpportunitySpecMutation(c.config, OpDelete)
	return &OpportunitySpecDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OpportunitySpecClient) DeleteOne(_m *OpportunitySpec) *OpportunitySpecDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OpportunitySpecClient) DeleteOneID(id string) *OpportunitySpecDeleteOne {
	builder := c.Delete().Where(opportunityspec.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OpportunitySpecDeleteOne{builder}
}

// Query returns a query builder for OpportunitySpec.
func (c *OpportunitySpecClient) Query() *OpportunitySpecQuery {
	return &OpportunitySpecQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOpportunitySpec},
		inters: c.Interceptors(),
	}
}

// Get returns a OpportunitySpec entity by its id.
func (c *OpportunitySpecClient) Get(ctx context.Context, id string) (*OpportunitySpec, error) {
	return c.Query().Where(opportunityspec.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OpportunitySpecClient) GetX(ctx context.Context, id string) *OpportunitySpec {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OpportunitySpecClient) Hooks() []Hook {
	return c.hooks.OpportunitySpec
}

// Interceptors returns the client interceptors.
func (c *OpportunitySpecClient) Interceptors() []Interceptor {
	return c.inters.OpportunitySpec
}

func (c *OpportunitySpecClient) mutate(ctx context.Context, m *OpportunitySpecMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OpportunitySpecCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OpportunitySpecUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OpportunitySpecUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OpportunitySpecDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OpportunitySpec mutation op: %q", m.Op())
	}
}

// PortfolioDimensionClient is a client for the PortfolioDimension schema.
type PortfolioDimensionClient struct {
	config
}

// NewPortfolioDimensionClient returns a client for the PortfolioDimension from the given config.
func NewPortfolioDimensionClient(c config) *PortfolioDimensionClient {
	return &PortfolioDimensionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `portfoliodimension.Hooks(f(g(h())))`.
func (c *PortfolioDimensionClient) Use(hooks ...Hook) {
	c.hooks.PortfolioDimension = append(c.hooks.PortfolioDimension, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `portfoliodimension.Intercept(f(g(h())))`.
func (c *PortfolioDimensionClient) Intercept(interceptors ...Interceptor) {
	c.inters.PortfolioDimension = append(c.inters.PortfolioDimension, interceptors...)
}

// Create returns a builder for creating a PortfolioDimension entity.
func (c *PortfolioDimensionClient) Create() *PortfolioDimensionCreate {
	mutation := newPortfolioDimensionMutation(c.config, OpCreate)
	return &PortfolioDimensionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PortfolioDimension entities.
func (c *PortfolioDimensionClient) CreateBulk(builders ...*PortfolioDimensionCreate) *PortfolioDimensionCreateBulk {
	return &PortfolioDimensionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PortfolioDimensionClient) MapCreateBulk(slice any, setFunc func(*PortfolioDimensionCreate, int)) *PortfolioDimensionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PortfolioDimensionCreateBulk{err: fmt.Errorf("calling to PortfolioDimensionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PortfolioDimensionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PortfolioDimensionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PortfolioDimension.
func (c *PortfolioDimensionClient) Update() *PortfolioDimensionUpdate {
	mutation := newPortfolioDimensionMutation(c.config, OpUpdate)
	return &PortfolioDimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PortfolioDimensionClient) UpdateOne(_m *PortfolioDimension) *PortfolioDimensionUpdateOne {
	mutation := newPortfolioDimensionMutation(c.config, OpUpdateOne, withPortfolioDimension(_m))
	return &PortfolioDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PortfolioDimensionClient) UpdateOneID(id string) *PortfolioDimensionUpdateOne {
	mutation := newPortfolioDimensionMutation(c.config, OpUpdateOne, withPortfolioDimensionID(id))
	return &PortfolioDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PortfolioDimension.
func (c *PortfolioDimensionClient) Delete() *PortfolioDimensionDelete {
	mutation := newPortfolioDimensionMutation(c.config, OpDelete)
	return &PortfolioDimensionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PortfolioDimensionClient) DeleteOne(_m *PortfolioDimension) *PortfolioDimensionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PortfolioDimensionClient) DeleteOneID(id string) *PortfolioDimensionDeleteOne {
	builder := c.Delete().Where(portfoliodimension.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PortfolioDimensionDeleteOne{builder}
}

// Query returns a query builder for PortfolioDimension.
func (c *PortfolioDimensionClient) Query() *PortfolioDimensionQuery {
	return &PortfolioDimensionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePortfolioDimension},
		inters: c.Interceptors(),
	}
}

// Get returns a PortfolioDimension entity by its id.
func (c *PortfolioDimensionClient) Get(ctx context.Context, id string) (*PortfolioDimension, error) {
	return c.Query().Where(portfoliodimension.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PortfolioDimensionClient) GetX(ctx context.Context, id string) *PortfolioDimension {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PortfolioDimensionClient) Hooks() []Hook {
	return c.hooks.PortfolioDimension
}

// Interceptors returns the client interceptors.
func (c *PortfolioDimensionClient) Interceptors() []Interceptor {
	return c.inters.PortfolioDimension
}

func (c *PortfolioDimensionClient) mutate(ctx context.Context, m *PortfolioDimensionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PortfolioDimensionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PortfolioDimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PortfolioDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PortfolioDimensionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PortfolioDimension mutation op: %q", m.Op())
	}
}

// RankOverrideClient is a client for the RankOverride schema.
type RankOverrideClient struct {
	config
}

// NewRankOverrideClient returns a client for the RankOverride from the given config.
func NewRankOverrideClient(c config) *RankOverrideClient {
	return &RankOverrideClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rankoverride.Hooks(f(g(h())))`.
func (c *RankOverrideClient) Use(hooks ...Hook) {
	c.hooks.RankOverride = append(c.hooks.RankOverride, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rankoverride.Intercept(f(g(h())))`.
func (c *RankOverrideClient) Intercept(interceptors ...Interceptor) {
	c.inters.RankOverride = append(c.inters.RankOverride, interceptors...)
}

// Create returns a builder for creating a RankOverride entity.
func (c *RankOverrideClient) Create() *RankOverrideCreate {
	mutation := newRankOverrideMutation(c.config, OpCreate)
	return &RankOverrideCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RankOverride entities.
func (c *RankOverrideClient) CreateBulk(builders ...*RankOverrideCreate) *RankOverrideCreateBulk {
	return &RankOverrideCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RankOverrideClient) MapCreateBulk(slice any, setFunc func(*RankOverrideCreate, int)) *RankOverrideCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RankOverrideCreateBulk{err: fmt.Errorf("calling to RankOverrideClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RankOverrideCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RankOverrideCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RankOverride.
func (c *RankOverrideClient) Update() *RankOverrideUpdate {
	mutation := newRankOverrideMutation(c.config, OpUpdate)
	return &RankOverrideUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RankOverrideClient) UpdateOne(_m *RankOverride) *RankOverrideUpdateOne {
	mutation := newRankOverrideMutation(c.config, OpUpdateOne, withRankOverride(_m))
	return &RankOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RankOverrideClient) UpdateOneID(id string) *RankOverrideUpdateOne {
	mutation := newRankOverrideMutation(c.config, OpUpdateOne, withRankOverrideID(id))
	return &RankOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RankOverride.
func (c *RankOverrideClient) Delete() *RankOverrideDelete {
	mutation := newRankOverrideMutation(c.config, OpDelete)
	return &RankOverrideDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RankOverrideClient) DeleteOne(_m *RankOverride) *RankOverrideDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RankOverrideClient) DeleteOneID(id string) *RankOverrideDeleteOne {
	builder := c.Delete().Where(rankoverride.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RankOverrideDeleteOne{builder}
}

// Query returns a query builder for RankOverride.
func (c *RankOverrideClient) Query() *RankOverrideQuery {
	return &RankOverrideQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRankOverride},
		inters: c.Interceptors(),
	}
}

// Get returns a RankOverride entity by its id.
func (c *RankOverrideClient) Get(ctx context.Context, id string) (*RankOverride, error) {
	return c.Query().Where(rankoverride.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RankOverrideClient) GetX(ctx context.Context, id string) *RankOverride {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RankOverrideClient) Hooks() []Hook {
	return c.hooks.RankOverride
}

// Interceptors returns the client interceptors.
func (c *RankOverrideClient) Interceptors() []Interceptor {
	return c.inters.RankOverride
}

func (c *RankOverrideClient) mutate(ctx context.Context, m *RankOverrideMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RankOverrideCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RankOverrideUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RankOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RankOverrideDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RankOverride mutation op: %q", m.Op())
	}
}

// ReleaseClient is a client for the Release schema.
type ReleaseClient struct {
	config
}

// NewReleaseClient returns a client for the Release from the given config.
func NewReleaseClient(c config) *ReleaseClient {
	return &ReleaseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `release.Hooks(f(g(h())))`.
func (c *ReleaseClient) Use(hooks ...Hook) {
	c.hooks.Release = append(c.hooks.Release, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `release.Intercept(f(g(h())))`.
func (c *ReleaseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Release = append(c.inters.Release, interceptors...)
}

// Create returns a builder for creating a Release entity.
func (c *ReleaseClient) Create() *ReleaseCreate {
	mutation := newReleaseMutation(c.config, OpCreate)
	return &ReleaseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Release entities.
func (c *ReleaseClient) CreateBulk(builders ...*ReleaseCreate) *ReleaseCreateBulk {
	return &ReleaseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReleaseClient) MapCreateBulk(slice any, setFunc func(*ReleaseCreate, int)) *ReleaseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReleaseCreateBulk{err: fmt.Errorf("calling to ReleaseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReleaseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReleaseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Release.
func (c *ReleaseClient) Update() *ReleaseUpdate {
	mutation := newReleaseMutation(c.config, OpUpdate)
	return &ReleaseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReleaseClient) UpdateOne(_m *Release) *ReleaseUpdateOne {
	mutation := newReleaseMutation(c.config, OpUpdateOne, withRelease(_m))
	return &ReleaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReleaseClient) UpdateOneID(id string) *ReleaseUpdateOne {
	mutation := newReleaseMutation(c.config, OpUpdateOne, withReleaseID(id))
	return &ReleaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Release.
func (c *ReleaseClient) Delete() *ReleaseDelete {
	mutation := newReleaseMutation(c.config, OpDelete)
	return &ReleaseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReleaseClient) DeleteOne(_m *Release) *ReleaseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReleaseClient) DeleteOneID(id string) *ReleaseDeleteOne {
	builder := c.Delete().Where(release.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReleaseDeleteOne{builder}
}

// Query returns a query builder for Release.
func (c *ReleaseClient) Query() *ReleaseQuery {
	return &ReleaseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRelease},
		inters: c.Interceptors(),
	}
}

// Get returns a Release entity by its id.
func (c *ReleaseClient) Get(ctx context.Context, id string) (*Release, error) {
	return c.Query().Where(release.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReleaseClient) GetX(ctx context.Context, id string) *Release {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ReleaseClient) Hooks() []Hook {
	return c.hooks.Release
}

// Interceptors returns the client interceptors.
func (c *ReleaseClient) Interceptors() []Interceptor {
	return c.inters.Release
}

func (c *ReleaseClient) mutate(ctx context.Context, m *ReleaseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReleaseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReleaseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReleaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReleaseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Release mutation op: %q", m.Op())
	}
}

// ReportDatasetClient is a client for the ReportDataset schema.
type ReportDatasetClient struct {
	config
}

// NewReportDatasetClient returns a client for the ReportDataset from the given config.
func NewReportDatasetClient(c config) *ReportDatasetClient {
	return &ReportDatasetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `reportdataset.Hooks(f(g(h())))`.
func (c *ReportDatasetClient) Use(hooks ...Hook) {
	c.hooks.ReportDataset = append(c.hooks.ReportDataset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `reportdataset.Intercept(f(g(h())))`.
func (c *ReportDatasetClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReportDataset = append(c.inters.ReportDataset, interceptors...)
}

// Create returns a builder for creating a ReportDataset entity.
func (c *ReportDatasetClient) Create() *ReportDatasetCreate {
	mutation := newReportDatasetMutation(c.config, OpCreate)
	return &ReportDatasetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReportDataset entities.
func (c *ReportDatasetClient) CreateBulk(builders ...*ReportDatasetCreate) *ReportDatasetCreateBulk {
	return &ReportDatasetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReportDatasetClient) MapCreateBulk(slice any, setFunc func(*ReportDatasetCreate, int)) *ReportDatasetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReportDatasetCreateBulk{err: fmt.Errorf("calling to ReportDatasetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReportDatasetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReportDatasetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReportDataset.
func (c *ReportDatasetClient) Update() *ReportDatasetUpdate {
	mutation := newReportDatasetMutation(c.config, OpUpdate)
	return &ReportDatasetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReportDatasetClient) UpdateOne(_m *ReportDataset) *ReportDatasetUpdateOne {
	mutation := newReportDatasetMutation(c.config, OpUpdateOne, withReportDataset(_m))
	return &ReportDatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReportDatasetClient) UpdateOneID(id string) *ReportDatasetUpdateOne {
	mutation := newReportDatasetMutation(c.config, OpUpdateOne, withReportDatasetID(id))
	return &ReportDatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReportDataset.
func (c *ReportDatasetClient) Delete() *ReportDatasetDelete {
	mutation := newReportDatasetMutation(c.config, OpDelete)
	return &ReportDatasetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReportDatasetClient) DeleteOne(_m *ReportDataset) *ReportDatasetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReportDatasetClient) DeleteOneID(id string) *ReportDatasetDeleteOne {
	builder := c.Delete().Where(reportdataset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReportDatasetDeleteOne{builder}
}

// Query returns a query builder for ReportDataset.
func (c *ReportDatasetClient) Query() *ReportDatasetQuery {
	return &ReportDatasetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReportDataset},
		inters: c.Interceptors(),
	}
}

// Get returns a ReportDataset entity by its id.
func (c *ReportDatasetClient) Get(ctx context.Context, id string) (*ReportDataset, error) {
	return c.Query().Where(reportdataset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReportDatasetClient) GetX(ctx context.Context, id string) *ReportDataset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ReportDatasetClient) Hooks() []Hook {
	return c.hooks.ReportDataset
}

// Interceptors returns the client interceptors.
func (c *ReportDatasetClient) Interceptors() []Interceptor {
	return c.inters.ReportDataset
}

func (c *ReportDatasetClient) mutate(ctx context.Context, m *ReportDatasetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReportDatasetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReportDatasetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReportDatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReportDatasetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReportDataset mutation op: %q", m.Op())
	}
}

// SyncMetaClient is a client for the SyncMeta schema.
type SyncMetaClient struct {
	config
}

// NewSyncMetaClient returns a client for the SyncMeta from the given config.
func NewSyncMetaClient(c config) *SyncMetaClient {
	return &SyncMetaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncmeta.Hooks(f(g(h())))`.
func (c *SyncMetaClient) Use(hooks ...Hook) {
	c.hooks.SyncMeta = append(c.hooks.SyncMeta, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncmeta.Intercept(f(g(h())))`.
func (c *SyncMetaClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncMeta = append(c.inters.SyncMeta, interceptors...)
}

// Create returns a builder for creating a SyncMeta entity.
func (c *SyncMetaClient) Create() *SyncMetaCreate {
	mutation := newSyncMetaMutation(c.config, OpCreate)
	return &SyncMetaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncMeta entities.
func (c *SyncMetaClient) CreateBulk(builders ...*SyncMetaCreate) *SyncMetaCreateBulk {
	return &SyncMetaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncMetaClient) MapCreateBulk(slice any, setFunc func(*SyncMetaCreate, int)) *SyncMetaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncMetaCreateBulk{err: fmt.Errorf("calling to SyncMetaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncMetaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncMetaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncMeta.
func (c *SyncMetaClient) Update() *SyncMetaUpdate {
	mutation := newSyncMetaMutation(c.config, OpUpdate)
	return &SyncMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncMetaClient) UpdateOne(_m *SyncMeta) *SyncMetaUpdateOne {
	mutation := newSyncMetaMutation(c.config, OpUpdateOne, withSyncMeta(_m))
	return &SyncMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncMetaClient) UpdateOneID(id int) *SyncMetaUpdateOne {
	mutation := newSyncMetaMutation(c.config, OpUpdateOne, withSyncMetaID(id))
	return &SyncMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncMeta.
func (c *SyncMetaClient) Delete() *SyncMetaDelete {
	mutation := newSyncMetaMutation(c.config, OpDelete)
	return &SyncMetaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncMetaClient) DeleteOne(_m *SyncMeta) *SyncMetaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncMetaClient) DeleteOneID(id int) *SyncMetaDeleteOne {
	builder := c.Delete().Where(syncmeta.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncMetaDeleteOne{builder}
}

// Query returns a query builder for SyncMeta.
func (c *SyncMetaClient) Query() *SyncMetaQuery {
	return &SyncMetaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncMeta},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncMeta entity by its id.
func (c *SyncMetaClient) Get(ctx context.Context, id int) (*SyncMeta, error) {
	return c.Query().Where(syncmeta.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncMetaClient) GetX(ctx context.Context, id int) *SyncMeta {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncMetaClient) Hooks() []Hook {
	return c.hooks.SyncMeta
}

// Interceptors returns the client interceptors.
func (c *SyncMetaClient) Interceptors() []Interceptor {
	return c.inters.SyncMeta
}

func (c *SyncMetaClient) mutate(ctx context.Context, m *SyncMetaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncMetaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncMetaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncMeta mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CustomFieldDef, DimensionOption, Evidence, Item, ItemAugment,
		OpportunityAssessment, OpportunitySpec, PortfolioDimension, RankOverride,
		Release, ReportDataset, SyncMeta []ent.Hook
	}
	inters struct {
		CustomFieldDef, DimensionOption, Evidence, Item, ItemAugment,
		OpportunityAssessment, OpportunitySpec, PortfolioDimension, RankOverride,
		Release, ReportDataset, SyncMeta []ent.Interceptor
	}
)
