// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/customfielddef"
)

// CustomFieldDefCreate is the builder for creating a CustomFieldDef entity.
type CustomFieldDefCreate struct {
	config
	mutation *CustomFieldDefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *CustomFieldDefCreate) SetProvider(v string) *CustomFieldDefCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *CustomFieldDefCreate) SetKey(v string) *CustomFieldDefCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CustomFieldDefCreate) SetName(v string) *CustomFieldDefCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CustomFieldDefCreate) SetNillableName(v *string) *CustomFieldDefCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetFieldType sets the "field_type" field.
func (_c *CustomFieldDefCreate) SetFieldType(v string) *CustomFieldDefCreate {
	_c.mutation.SetFieldType(v)
	return _c
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_c *CustomFieldDefCreate) SetNillableFieldType(v *string) *CustomFieldDefCreate {
	if v != nil {
		_c.SetFieldType(*v)
	}
	return _c
}

// SetKinds sets the "kinds" field.
func (_c *CustomFieldDefCreate) SetKinds(v []string) *CustomFieldDefCreate {
	_c.mutation.SetKinds(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CustomFieldDefCreate) SetMetadata(v map[string]interface{}) *CustomFieldDefCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *CustomFieldDefCreate) SetSyncedAt(v time.Time) *CustomFieldDefCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *CustomFieldDefCreate) SetNillableSyncedAt(v *time.Time) *CustomFieldDefCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomFieldDefCreate) SetID(v string) *CustomFieldDefCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CustomFieldDefMutation object of the builder.
func (_c *CustomFieldDefCreate) Mutation() *CustomFieldDefMutation {
	return _c.mutation
}

// Save creates the CustomFieldDef in the database.
func (_c *CustomFieldDefCreate) Save(ctx context.Context) (*CustomFieldDef, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomFieldDefCreate) SaveX(ctx context.Context) *CustomFieldDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFieldDefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFieldDefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomFieldDefCreate) defaults() {
	if _, ok := _c.mutation.SyncedAt(); !ok {
		v := customfielddef.DefaultSyncedAt()
		_c.mutation.SetSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomFieldDefCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "CustomFieldDef.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := customfielddef.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "CustomFieldDef.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "CustomFieldDef.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := customfielddef.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CustomFieldDef.key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := customfielddef.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CustomFieldDef.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FieldType(); ok {
		if err := customfielddef.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "CustomFieldDef.field_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "CustomFieldDef.synced_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := customfielddef.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CustomFieldDef.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CustomFieldDefCreate) sqlSave(ctx context.Context) (*CustomFieldDef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CustomFieldDef.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomFieldDefCreate) createSpec() (*CustomFieldDef, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomFieldDef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customfielddef.Table, sqlgraph.NewFieldSpec(customfielddef.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(customfielddef.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(customfielddef.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(customfielddef.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FieldType(); ok {
		_spec.SetField(customfielddef.FieldFieldType, field.TypeString, value)
		_node.FieldType = value
	}
	if value, ok := _c.mutation.Kinds(); ok {
		_spec.SetField(customfielddef.FieldKinds, field.TypeJSON, value)
		_node.Kinds = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(customfielddef.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(customfielddef.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomFieldDef.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomFieldDefUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomFieldDefCreate) OnConflict(opts ...sql.ConflictOption) *CustomFieldDefUpsertOne {
	_c.conflict = opts
	return &CustomFieldDefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomFieldDefCreate) OnConflictColumns(columns ...string) *CustomFieldDefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomFieldDefUpsertOne{
		create: _c,
	}
}

type (
	// CustomFieldDefUpsertOne is the builder for "upsert"-ing
	//  one CustomFieldDef node.
	CustomFieldDefUpsertOne struct {
		create *CustomFieldDefCreate
	}

	// CustomFieldDefUpsert is the "OnConflict" setter.
	CustomFieldDefUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *CustomFieldDefUpsert) SetProvider(v string) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateProvider() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldProvider)
	return u
}

// SetKey sets the "key" field.
func (u *CustomFieldDefUpsert) SetKey(v string) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateKey() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldKey)
	return u
}

// SetName sets the "name" field.
func (u *CustomFieldDefUpsert) SetName(v string) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateName() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *CustomFieldDefUpsert) ClearName() *CustomFieldDefUpsert {
	u.SetNull(customfielddef.FieldName)
	return u
}

// SetFieldType sets the "field_type" field.
func (u *CustomFieldDefUpsert) SetFieldType(v string) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldFieldType, v)
	return u
}

// UpdateFieldType sets the "field_type" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateFieldType() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldFieldType)
	return u
}

// ClearFieldType clears the value of the "field_type" field.
func (u *CustomFieldDefUpsert) ClearFieldType() *CustomFieldDefUpsert {
	u.SetNull(customfielddef.FieldFieldType)
	return u
}

// SetKinds sets the "kinds" field.
func (u *CustomFieldDefUpsert) SetKinds(v []string) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldKinds, v)
	return u
}

// UpdateKinds sets the "kinds" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateKinds() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldKinds)
	return u
}

// ClearKinds clears the value of the "kinds" field.
func (u *CustomFieldDefUpsert) ClearKinds() *CustomFieldDefUpsert {
	u.SetNull(customfielddef.FieldKinds)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *CustomFieldDefUpsert) SetMetadata(v map[string]interface{}) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateMetadata() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CustomFieldDefUpsert) ClearMetadata() *CustomFieldDefUpsert {
	u.SetNull(customfielddef.FieldMetadata)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *CustomFieldDefUpsert) SetSyncedAt(v time.Time) *CustomFieldDefUpsert {
	u.Set(customfielddef.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *CustomFieldDefUpsert) UpdateSyncedAt() *CustomFieldDefUpsert {
	u.SetExcluded(customfielddef.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customfielddef.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomFieldDefUpsertOne) UpdateNewValues() *CustomFieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customfielddef.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomFieldDefUpsertOne) Ignore() *CustomFieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomFieldDefUpsertOne) DoNothing() *CustomFieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomFieldDefCreate.OnConflict
// documentation for more info.
func (u *CustomFieldDefUpsertOne) Update(set func(*CustomFieldDefUpsert)) *CustomFieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomFieldDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *CustomFieldDefUpsertOne) SetProvider(v string) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateProvider() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateProvider()
	})
}

// SetKey sets the "key" field.
func (u *CustomFieldDefUpsertOne) SetKey(v string) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateKey() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *CustomFieldDefUpsertOne) SetName(v string) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateName() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CustomFieldDefUpsertOne) ClearName() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearName()
	})
}

// SetFieldType sets the "field_type" field.
func (u *CustomFieldDefUpsertOne) SetFieldType(v string) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetFieldType(v)
	})
}

// UpdateFieldType sets the "field_type" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateFieldType() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateFieldType()
	})
}

// ClearFieldType clears the value of the "field_type" field.
func (u *CustomFieldDefUpsertOne) ClearFieldType() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearFieldType()
	})
}

// SetKinds sets the "kinds" field.
func (u *CustomFieldDefUpsertOne) SetKinds(v []string) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetKinds(v)
	})
}

// UpdateKinds sets the "kinds" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateKinds() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateKinds()
	})
}

// ClearKinds clears the value of the "kinds" field.
func (u *CustomFieldDefUpsertOne) ClearKinds() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearKinds()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CustomFieldDefUpsertOne) SetMetadata(v map[string]interface{}) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateMetadata() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CustomFieldDefUpsertOne) ClearMetadata() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearMetadata()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *CustomFieldDefUpsertOne) SetSyncedAt(v time.Time) *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *CustomFieldDefUpsertOne) UpdateSyncedAt() *CustomFieldDefUpsertOne {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *CustomFieldDefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomFieldDefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomFieldDefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomFieldDefUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CustomFieldDefUpsertOne.ID is not supported by MySQL driver. Use CustomFieldDefUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomFieldDefUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomFieldDefCreateBulk is the builder for creating many CustomFieldDef entities in bulk.
type CustomFieldDefCreateBulk struct {
	config
	err      error
	builders []*CustomFieldDefCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomFieldDef entities in the database.
func (_c *CustomFieldDefCreateBulk) Save(ctx context.Context) ([]*CustomFieldDef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomFieldDef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomFieldDefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomFieldDefCreateBulk) SaveX(ctx context.Context) []*CustomFieldDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFieldDefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFieldDefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomFieldDef.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomFieldDefUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomFieldDefCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomFieldDefUpsertBulk {
	_c.conflict = opts
	return &CustomFieldDefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomFieldDefCreateBulk) OnConflictColumns(columns ...string) *CustomFieldDefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomFieldDefUpsertBulk{
		create: _c,
	}
}

// CustomFieldDefUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomFieldDef nodes.
type CustomFieldDefUpsertBulk struct {
	create *CustomFieldDefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customfielddef.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomFieldDefUpsertBulk) UpdateNewValues() *CustomFieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customfielddef.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomFieldDef.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomFieldDefUpsertBulk) Ignore() *CustomFieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomFieldDefUpsertBulk) DoNothing() *CustomFieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomFieldDefCreateBulk.OnConflict
// documentation for more info.
func (u *CustomFieldDefUpsertBulk) Update(set func(*CustomFieldDefUpsert)) *CustomFieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomFieldDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *CustomFieldDefUpsertBulk) SetProvider(v string) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateProvider() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateProvider()
	})
}

// SetKey sets the "key" field.
func (u *CustomFieldDefUpsertBulk) SetKey(v string) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateKey() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *CustomFieldDefUpsertBulk) SetName(v string) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateName() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CustomFieldDefUpsertBulk) ClearName() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearName()
	})
}

// SetFieldType sets the "field_type" field.
func (u *CustomFieldDefUpsertBulk) SetFieldType(v string) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetFieldType(v)
	})
}

// UpdateFieldType sets the "field_type" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateFieldType() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateFieldType()
	})
}

// ClearFieldType clears the value of the "field_type" field.
func (u *CustomFieldDefUpsertBulk) ClearFieldType() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearFieldType()
	})
}

// SetKinds sets the "kinds" field.
func (u *CustomFieldDefUpsertBulk) SetKinds(v []string) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetKinds(v)
	})
}

// UpdateKinds sets the "kinds" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateKinds() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateKinds()
	})
}

// ClearKinds clears the value of the "kinds" field.
func (u *CustomFieldDefUpsertBulk) ClearKinds() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearKinds()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CustomFieldDefUpsertBulk) SetMetadata(v map[string]interface{}) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateMetadata() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *CustomFieldDefUpsertBulk) ClearMetadata() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.ClearMetadata()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *CustomFieldDefUpsertBulk) SetSyncedAt(v time.Time) *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *CustomFieldDefUpsertBulk) UpdateSyncedAt() *CustomFieldDefUpsertBulk {
	return u.Update(func(s *CustomFieldDefUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *CustomFieldDefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomFieldDefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomFieldDefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomFieldDefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
