// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/dimensionoption"
	"github.com/grokify/omniroadmap/ent/predicate"
	"github.com/grokify/prism-roadmap/assessment"
)

// DimensionOptionUpdate is the builder for updating DimensionOption entities.
type DimensionOptionUpdate struct {
	config
	hooks    []Hook
	mutation *DimensionOptionMutation
}

// Where appends a list predicates to the DimensionOptionUpdate builder.
func (_u *DimensionOptionUpdate) Where(ps ...predicate.DimensionOption) *DimensionOptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDimensionRowID sets the "dimension_row_id" field.
func (_u *DimensionOptionUpdate) SetDimensionRowID(v string) *DimensionOptionUpdate {
	_u.mutation.SetDimensionRowID(v)
	return _u
}

// SetNillableDimensionRowID sets the "dimension_row_id" field if the given value is not nil.
func (_u *DimensionOptionUpdate) SetNillableDimensionRowID(v *string) *DimensionOptionUpdate {
	if v != nil {
		_u.SetDimensionRowID(*v)
	}
	return _u
}

// SetOptionID sets the "option_id" field.
func (_u *DimensionOptionUpdate) SetOptionID(v string) *DimensionOptionUpdate {
	_u.mutation.SetOptionID(v)
	return _u
}

// SetNillableOptionID sets the "option_id" field if the given value is not nil.
func (_u *DimensionOptionUpdate) SetNillableOptionID(v *string) *DimensionOptionUpdate {
	if v != nil {
		_u.SetOptionID(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *DimensionOptionUpdate) SetLabel(v string) *DimensionOptionUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DimensionOptionUpdate) SetNillableLabel(v *string) *DimensionOptionUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetQuestions sets the "questions" field.
func (_u *DimensionOptionUpdate) SetQuestions(v []assessment.DimensionQuestion) *DimensionOptionUpdate {
	_u.mutation.SetQuestions(v)
	return _u
}

// AppendQuestions appends value to the "questions" field.
func (_u *DimensionOptionUpdate) AppendQuestions(v []assessment.DimensionQuestion) *DimensionOptionUpdate {
	_u.mutation.AppendQuestions(v)
	return _u
}

// ClearQuestions clears the value of the "questions" field.
func (_u *DimensionOptionUpdate) ClearQuestions() *DimensionOptionUpdate {
	_u.mutation.ClearQuestions()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *DimensionOptionUpdate) SetSequence(v int) *DimensionOptionUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *DimensionOptionUpdate) SetNillableSequence(v *int) *DimensionOptionUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *DimensionOptionUpdate) AddSequence(v int) *DimensionOptionUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// Mutation returns the DimensionOptionMutation object of the builder.
func (_u *DimensionOptionUpdate) Mutation() *DimensionOptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DimensionOptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DimensionOptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DimensionOptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DimensionOptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DimensionOptionUpdate) check() error {
	if v, ok := _u.mutation.DimensionRowID(); ok {
		if err := dimensionoption.DimensionRowIDValidator(v); err != nil {
			return &ValidationError{Name: "dimension_row_id", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.dimension_row_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OptionID(); ok {
		if err := dimensionoption.OptionIDValidator(v); err != nil {
			return &ValidationError{Name: "option_id", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.option_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := dimensionoption.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.label": %w`, err)}
		}
	}
	return nil
}

func (_u *DimensionOptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dimensionoption.Table, dimensionoption.Columns, sqlgraph.NewFieldSpec(dimensionoption.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DimensionRowID(); ok {
		_spec.SetField(dimensionoption.FieldDimensionRowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OptionID(); ok {
		_spec.SetField(dimensionoption.FieldOptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(dimensionoption.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Questions(); ok {
		_spec.SetField(dimensionoption.FieldQuestions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQuestions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dimensionoption.FieldQuestions, value)
		})
	}
	if _u.mutation.QuestionsCleared() {
		_spec.ClearField(dimensionoption.FieldQuestions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(dimensionoption.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(dimensionoption.FieldSequence, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dimensionoption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DimensionOptionUpdateOne is the builder for updating a single DimensionOption entity.
type DimensionOptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DimensionOptionMutation
}

// SetDimensionRowID sets the "dimension_row_id" field.
func (_u *DimensionOptionUpdateOne) SetDimensionRowID(v string) *DimensionOptionUpdateOne {
	_u.mutation.SetDimensionRowID(v)
	return _u
}

// SetNillableDimensionRowID sets the "dimension_row_id" field if the given value is not nil.
func (_u *DimensionOptionUpdateOne) SetNillableDimensionRowID(v *string) *DimensionOptionUpdateOne {
	if v != nil {
		_u.SetDimensionRowID(*v)
	}
	return _u
}

// SetOptionID sets the "option_id" field.
func (_u *DimensionOptionUpdateOne) SetOptionID(v string) *DimensionOptionUpdateOne {
	_u.mutation.SetOptionID(v)
	return _u
}

// SetNillableOptionID sets the "option_id" field if the given value is not nil.
func (_u *DimensionOptionUpdateOne) SetNillableOptionID(v *string) *DimensionOptionUpdateOne {
	if v != nil {
		_u.SetOptionID(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *DimensionOptionUpdateOne) SetLabel(v string) *DimensionOptionUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DimensionOptionUpdateOne) SetNillableLabel(v *string) *DimensionOptionUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetQuestions sets the "questions" field.
func (_u *DimensionOptionUpdateOne) SetQuestions(v []assessment.DimensionQuestion) *DimensionOptionUpdateOne {
	_u.mutation.SetQuestions(v)
	return _u
}

// AppendQuestions appends value to the "questions" field.
func (_u *DimensionOptionUpdateOne) AppendQuestions(v []assessment.DimensionQuestion) *DimensionOptionUpdateOne {
	_u.mutation.AppendQuestions(v)
	return _u
}

// ClearQuestions clears the value of the "questions" field.
func (_u *DimensionOptionUpdateOne) ClearQuestions() *DimensionOptionUpdateOne {
	_u.mutation.ClearQuestions()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *DimensionOptionUpdateOne) SetSequence(v int) *DimensionOptionUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *DimensionOptionUpdateOne) SetNillableSequence(v *int) *DimensionOptionUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *DimensionOptionUpdateOne) AddSequence(v int) *DimensionOptionUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// Mutation returns the DimensionOptionMutation object of the builder.
func (_u *DimensionOptionUpdateOne) Mutation() *DimensionOptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the DimensionOptionUpdate builder.
func (_u *DimensionOptionUpdateOne) Where(ps ...predicate.DimensionOption) *DimensionOptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DimensionOptionUpdateOne) Select(field string, fields ...string) *DimensionOptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DimensionOption entity.
func (_u *DimensionOptionUpdateOne) Save(ctx context.Context) (*DimensionOption, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DimensionOptionUpdateOne) SaveX(ctx context.Context) *DimensionOption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DimensionOptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DimensionOptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DimensionOptionUpdateOne) check() error {
	if v, ok := _u.mutation.DimensionRowID(); ok {
		if err := dimensionoption.DimensionRowIDValidator(v); err != nil {
			return &ValidationError{Name: "dimension_row_id", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.dimension_row_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OptionID(); ok {
		if err := dimensionoption.OptionIDValidator(v); err != nil {
			return &ValidationError{Name: "option_id", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.option_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := dimensionoption.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "DimensionOption.label": %w`, err)}
		}
	}
	return nil
}

func (_u *DimensionOptionUpdateOne) sqlSave(ctx context.Context) (_node *DimensionOption, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dimensionoption.Table, dimensionoption.Columns, sqlgraph.NewFieldSpec(dimensionoption.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DimensionOption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dimensionoption.FieldID)
		for _, f := range fields {
			if !dimensionoption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dimensionoption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DimensionRowID(); ok {
		_spec.SetField(dimensionoption.FieldDimensionRowID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OptionID(); ok {
		_spec.SetField(dimensionoption.FieldOptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(dimensionoption.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Questions(); ok {
		_spec.SetField(dimensionoption.FieldQuestions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQuestions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dimensionoption.FieldQuestions, value)
		})
	}
	if _u.mutation.QuestionsCleared() {
		_spec.ClearField(dimensionoption.FieldQuestions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(dimensionoption.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(dimensionoption.FieldSequence, field.TypeInt, value)
	}
	_node = &DimensionOption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dimensionoption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
