// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/evidence"
	"github.com/grokify/omniroadmap/ent/predicate"
	"github.com/grokify/prism-roadmap/assessment"
)

// EvidenceUpdate is the builder for updating Evidence entities.
type EvidenceUpdate struct {
	config
	hooks    []Hook
	mutation *EvidenceMutation
}

// Where appends a list predicates to the EvidenceUpdate builder.
func (_u *EvidenceUpdate) Where(ps ...predicate.Evidence) *EvidenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSystem sets the "system" field.
func (_u *EvidenceUpdate) SetSystem(v string) *EvidenceUpdate {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableSystem(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// ClearSystem clears the value of the "system" field.
func (_u *EvidenceUpdate) ClearSystem() *EvidenceUpdate {
	_u.mutation.ClearSystem()
	return _u
}

// SetSensitivity sets the "sensitivity" field.
func (_u *EvidenceUpdate) SetSensitivity(v string) *EvidenceUpdate {
	_u.mutation.SetSensitivity(v)
	return _u
}

// SetNillableSensitivity sets the "sensitivity" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableSensitivity(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetSensitivity(*v)
	}
	return _u
}

// ClearSensitivity clears the value of the "sensitivity" field.
func (_u *EvidenceUpdate) ClearSensitivity() *EvidenceUpdate {
	_u.mutation.ClearSensitivity()
	return _u
}

// SetCapturedBy sets the "captured_by" field.
func (_u *EvidenceUpdate) SetCapturedBy(v string) *EvidenceUpdate {
	_u.mutation.SetCapturedBy(v)
	return _u
}

// SetNillableCapturedBy sets the "captured_by" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableCapturedBy(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetCapturedBy(*v)
	}
	return _u
}

// ClearCapturedBy clears the value of the "captured_by" field.
func (_u *EvidenceUpdate) ClearCapturedBy() *EvidenceUpdate {
	_u.mutation.ClearCapturedBy()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *EvidenceUpdate) SetCapturedAt(v time.Time) *EvidenceUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableCapturedAt(v *time.Time) *EvidenceUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *EvidenceUpdate) ClearCapturedAt() *EvidenceUpdate {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetSourceURI sets the "source_uri" field.
func (_u *EvidenceUpdate) SetSourceURI(v string) *EvidenceUpdate {
	_u.mutation.SetSourceURI(v)
	return _u
}

// SetNillableSourceURI sets the "source_uri" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableSourceURI(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetSourceURI(*v)
	}
	return _u
}

// ClearSourceURI clears the value of the "source_uri" field.
func (_u *EvidenceUpdate) ClearSourceURI() *EvidenceUpdate {
	_u.mutation.ClearSourceURI()
	return _u
}

// SetVerified sets the "verified" field.
func (_u *EvidenceUpdate) SetVerified(v bool) *EvidenceUpdate {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableVerified(v *bool) *EvidenceUpdate {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetCanonical sets the "canonical" field.
func (_u *EvidenceUpdate) SetCanonical(v assessment.Evidence) *EvidenceUpdate {
	_u.mutation.SetCanonical(v)
	return _u
}

// SetNillableCanonical sets the "canonical" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableCanonical(v *assessment.Evidence) *EvidenceUpdate {
	if v != nil {
		_u.SetCanonical(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvidenceUpdate) SetUpdatedAt(v time.Time) *EvidenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvidenceMutation object of the builder.
func (_u *EvidenceUpdate) Mutation() *EvidenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvidenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvidenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvidenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvidenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvidenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvidenceUpdate) check() error {
	if v, ok := _u.mutation.System(); ok {
		if err := evidence.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "Evidence.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sensitivity(); ok {
		if err := evidence.SensitivityValidator(v); err != nil {
			return &ValidationError{Name: "sensitivity", err: fmt.Errorf(`ent: validator failed for field "Evidence.sensitivity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CapturedBy(); ok {
		if err := evidence.CapturedByValidator(v); err != nil {
			return &ValidationError{Name: "captured_by", err: fmt.Errorf(`ent: validator failed for field "Evidence.captured_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURI(); ok {
		if err := evidence.SourceURIValidator(v); err != nil {
			return &ValidationError{Name: "source_uri", err: fmt.Errorf(`ent: validator failed for field "Evidence.source_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Canonical(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "canonical", err: fmt.Errorf(`ent: validator failed for field "Evidence.canonical": %w`, err)}
		}
	}
	return nil
}

func (_u *EvidenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evidence.Table, evidence.Columns, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(evidence.FieldSystem, field.TypeString, value)
	}
	if _u.mutation.SystemCleared() {
		_spec.ClearField(evidence.FieldSystem, field.TypeString)
	}
	if value, ok := _u.mutation.Sensitivity(); ok {
		_spec.SetField(evidence.FieldSensitivity, field.TypeString, value)
	}
	if _u.mutation.SensitivityCleared() {
		_spec.ClearField(evidence.FieldSensitivity, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedBy(); ok {
		_spec.SetField(evidence.FieldCapturedBy, field.TypeString, value)
	}
	if _u.mutation.CapturedByCleared() {
		_spec.ClearField(evidence.FieldCapturedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(evidence.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(evidence.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceURI(); ok {
		_spec.SetField(evidence.FieldSourceURI, field.TypeString, value)
	}
	if _u.mutation.SourceURICleared() {
		_spec.ClearField(evidence.FieldSourceURI, field.TypeString)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(evidence.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Canonical(); ok {
		_spec.SetField(evidence.FieldCanonical, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvidenceUpdateOne is the builder for updating a single Evidence entity.
type EvidenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvidenceMutation
}

// SetSystem sets the "system" field.
func (_u *EvidenceUpdateOne) SetSystem(v string) *EvidenceUpdateOne {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableSystem(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// ClearSystem clears the value of the "system" field.
func (_u *EvidenceUpdateOne) ClearSystem() *EvidenceUpdateOne {
	_u.mutation.ClearSystem()
	return _u
}

// SetSensitivity sets the "sensitivity" field.
func (_u *EvidenceUpdateOne) SetSensitivity(v string) *EvidenceUpdateOne {
	_u.mutation.SetSensitivity(v)
	return _u
}

// SetNillableSensitivity sets the "sensitivity" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableSensitivity(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetSensitivity(*v)
	}
	return _u
}

// ClearSensitivity clears the value of the "sensitivity" field.
func (_u *EvidenceUpdateOne) ClearSensitivity() *EvidenceUpdateOne {
	_u.mutation.ClearSensitivity()
	return _u
}

// SetCapturedBy sets the "captured_by" field.
func (_u *EvidenceUpdateOne) SetCapturedBy(v string) *EvidenceUpdateOne {
	_u.mutation.SetCapturedBy(v)
	return _u
}

// SetNillableCapturedBy sets the "captured_by" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableCapturedBy(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetCapturedBy(*v)
	}
	return _u
}

// ClearCapturedBy clears the value of the "captured_by" field.
func (_u *EvidenceUpdateOne) ClearCapturedBy() *EvidenceUpdateOne {
	_u.mutation.ClearCapturedBy()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *EvidenceUpdateOne) SetCapturedAt(v time.Time) *EvidenceUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableCapturedAt(v *time.Time) *EvidenceUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *EvidenceUpdateOne) ClearCapturedAt() *EvidenceUpdateOne {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetSourceURI sets the "source_uri" field.
func (_u *EvidenceUpdateOne) SetSourceURI(v string) *EvidenceUpdateOne {
	_u.mutation.SetSourceURI(v)
	return _u
}

// SetNillableSourceURI sets the "source_uri" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableSourceURI(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetSourceURI(*v)
	}
	return _u
}

// ClearSourceURI clears the value of the "source_uri" field.
func (_u *EvidenceUpdateOne) ClearSourceURI() *EvidenceUpdateOne {
	_u.mutation.ClearSourceURI()
	return _u
}

// SetVerified sets the "verified" field.
func (_u *EvidenceUpdateOne) SetVerified(v bool) *EvidenceUpdateOne {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableVerified(v *bool) *EvidenceUpdateOne {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetCanonical sets the "canonical" field.
func (_u *EvidenceUpdateOne) SetCanonical(v assessment.Evidence) *EvidenceUpdateOne {
	_u.mutation.SetCanonical(v)
	return _u
}

// SetNillableCanonical sets the "canonical" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableCanonical(v *assessment.Evidence) *EvidenceUpdateOne {
	if v != nil {
		_u.SetCanonical(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvidenceUpdateOne) SetUpdatedAt(v time.Time) *EvidenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EvidenceMutation object of the builder.
func (_u *EvidenceUpdateOne) Mutation() *EvidenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the EvidenceUpdate builder.
func (_u *EvidenceUpdateOne) Where(ps ...predicate.Evidence) *EvidenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvidenceUpdateOne) Select(field string, fields ...string) *EvidenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Evidence entity.
func (_u *EvidenceUpdateOne) Save(ctx context.Context) (*Evidence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvidenceUpdateOne) SaveX(ctx context.Context) *Evidence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvidenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvidenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvidenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvidenceUpdateOne) check() error {
	if v, ok := _u.mutation.System(); ok {
		if err := evidence.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "Evidence.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sensitivity(); ok {
		if err := evidence.SensitivityValidator(v); err != nil {
			return &ValidationError{Name: "sensitivity", err: fmt.Errorf(`ent: validator failed for field "Evidence.sensitivity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CapturedBy(); ok {
		if err := evidence.CapturedByValidator(v); err != nil {
			return &ValidationError{Name: "captured_by", err: fmt.Errorf(`ent: validator failed for field "Evidence.captured_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURI(); ok {
		if err := evidence.SourceURIValidator(v); err != nil {
			return &ValidationError{Name: "source_uri", err: fmt.Errorf(`ent: validator failed for field "Evidence.source_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Canonical(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "canonical", err: fmt.Errorf(`ent: validator failed for field "Evidence.canonical": %w`, err)}
		}
	}
	return nil
}

func (_u *EvidenceUpdateOne) sqlSave(ctx context.Context) (_node *Evidence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evidence.Table, evidence.Columns, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Evidence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evidence.FieldID)
		for _, f := range fields {
			if !evidence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evidence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(evidence.FieldSystem, field.TypeString, value)
	}
	if _u.mutation.SystemCleared() {
		_spec.ClearField(evidence.FieldSystem, field.TypeString)
	}
	if value, ok := _u.mutation.Sensitivity(); ok {
		_spec.SetField(evidence.FieldSensitivity, field.TypeString, value)
	}
	if _u.mutation.SensitivityCleared() {
		_spec.ClearField(evidence.FieldSensitivity, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedBy(); ok {
		_spec.SetField(evidence.FieldCapturedBy, field.TypeString, value)
	}
	if _u.mutation.CapturedByCleared() {
		_spec.ClearField(evidence.FieldCapturedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(evidence.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(evidence.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceURI(); ok {
		_spec.SetField(evidence.FieldSourceURI, field.TypeString, value)
	}
	if _u.mutation.SourceURICleared() {
		_spec.ClearField(evidence.FieldSourceURI, field.TypeString)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(evidence.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Canonical(); ok {
		_spec.SetField(evidence.FieldCanonical, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Evidence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
