// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/evidence"
	"github.com/grokify/prism-roadmap/assessment"
)

// EvidenceCreate is the builder for creating a Evidence entity.
type EvidenceCreate struct {
	config
	mutation *EvidenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSystem sets the "system" field.
func (_c *EvidenceCreate) SetSystem(v string) *EvidenceCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableSystem(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetSystem(*v)
	}
	return _c
}

// SetSensitivity sets the "sensitivity" field.
func (_c *EvidenceCreate) SetSensitivity(v string) *EvidenceCreate {
	_c.mutation.SetSensitivity(v)
	return _c
}

// SetNillableSensitivity sets the "sensitivity" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableSensitivity(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetSensitivity(*v)
	}
	return _c
}

// SetCapturedBy sets the "captured_by" field.
func (_c *EvidenceCreate) SetCapturedBy(v string) *EvidenceCreate {
	_c.mutation.SetCapturedBy(v)
	return _c
}

// SetNillableCapturedBy sets the "captured_by" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableCapturedBy(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetCapturedBy(*v)
	}
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *EvidenceCreate) SetCapturedAt(v time.Time) *EvidenceCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableCapturedAt(v *time.Time) *EvidenceCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetSourceURI sets the "source_uri" field.
func (_c *EvidenceCreate) SetSourceURI(v string) *EvidenceCreate {
	_c.mutation.SetSourceURI(v)
	return _c
}

// SetNillableSourceURI sets the "source_uri" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableSourceURI(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetSourceURI(*v)
	}
	return _c
}

// SetVerified sets the "verified" field.
func (_c *EvidenceCreate) SetVerified(v bool) *EvidenceCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableVerified(v *bool) *EvidenceCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetCanonical sets the "canonical" field.
func (_c *EvidenceCreate) SetCanonical(v assessment.Evidence) *EvidenceCreate {
	_c.mutation.SetCanonical(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EvidenceCreate) SetCreatedAt(v time.Time) *EvidenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableCreatedAt(v *time.Time) *EvidenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EvidenceCreate) SetUpdatedAt(v time.Time) *EvidenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableUpdatedAt(v *time.Time) *EvidenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EvidenceCreate) SetID(v string) *EvidenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EvidenceMutation object of the builder.
func (_c *EvidenceCreate) Mutation() *EvidenceMutation {
	return _c.mutation
}

// Save creates the Evidence in the database.
func (_c *EvidenceCreate) Save(ctx context.Context) (*Evidence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EvidenceCreate) SaveX(ctx context.Context) *Evidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvidenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvidenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EvidenceCreate) defaults() {
	if _, ok := _c.mutation.Verified(); !ok {
		v := evidence.DefaultVerified
		_c.mutation.SetVerified(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := evidence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := evidence.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EvidenceCreate) check() error {
	if v, ok := _c.mutation.System(); ok {
		if err := evidence.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "Evidence.system": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Sensitivity(); ok {
		if err := evidence.SensitivityValidator(v); err != nil {
			return &ValidationError{Name: "sensitivity", err: fmt.Errorf(`ent: validator failed for field "Evidence.sensitivity": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CapturedBy(); ok {
		if err := evidence.CapturedByValidator(v); err != nil {
			return &ValidationError{Name: "captured_by", err: fmt.Errorf(`ent: validator failed for field "Evidence.captured_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceURI(); ok {
		if err := evidence.SourceURIValidator(v); err != nil {
			return &ValidationError{Name: "source_uri", err: fmt.Errorf(`ent: validator failed for field "Evidence.source_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "Evidence.verified"`)}
	}
	if _, ok := _c.mutation.Canonical(); !ok {
		return &ValidationError{Name: "canonical", err: errors.New(`ent: missing required field "Evidence.canonical"`)}
	}
	if v, ok := _c.mutation.Canonical(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "canonical", err: fmt.Errorf(`ent: validator failed for field "Evidence.canonical": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Evidence.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Evidence.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := evidence.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Evidence.id": %w`, err)}
		}
	}
	return nil
}

func (_c *EvidenceCreate) sqlSave(ctx context.Context) (*Evidence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Evidence.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EvidenceCreate) createSpec() (*Evidence, *sqlgraph.CreateSpec) {
	var (
		_node = &Evidence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(evidence.Table, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(evidence.FieldSystem, field.TypeString, value)
		_node.System = value
	}
	if value, ok := _c.mutation.Sensitivity(); ok {
		_spec.SetField(evidence.FieldSensitivity, field.TypeString, value)
		_node.Sensitivity = value
	}
	if value, ok := _c.mutation.CapturedBy(); ok {
		_spec.SetField(evidence.FieldCapturedBy, field.TypeString, value)
		_node.CapturedBy = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(evidence.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = &value
	}
	if value, ok := _c.mutation.SourceURI(); ok {
		_spec.SetField(evidence.FieldSourceURI, field.TypeString, value)
		_node.SourceURI = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(evidence.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.Canonical(); ok {
		_spec.SetField(evidence.FieldCanonical, field.TypeJSON, value)
		_node.Canonical = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(evidence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Evidence.Create().
//		SetSystem(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvidenceUpsert) {
//			SetSystem(v+v).
//		}).
//		Exec(ctx)
func (_c *EvidenceCreate) OnConflict(opts ...sql.ConflictOption) *EvidenceUpsertOne {
	_c.conflict = opts
	return &EvidenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Evidence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvidenceCreate) OnConflictColumns(columns ...string) *EvidenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvidenceUpsertOne{
		create: _c,
	}
}

type (
	// EvidenceUpsertOne is the builder for "upsert"-ing
	//  one Evidence node.
	EvidenceUpsertOne struct {
		create *EvidenceCreate
	}

	// EvidenceUpsert is the "OnConflict" setter.
	EvidenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetSystem sets the "system" field.
func (u *EvidenceUpsert) SetSystem(v string) *EvidenceUpsert {
	u.Set(evidence.FieldSystem, v)
	return u
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateSystem() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldSystem)
	return u
}

// ClearSystem clears the value of the "system" field.
func (u *EvidenceUpsert) ClearSystem() *EvidenceUpsert {
	u.SetNull(evidence.FieldSystem)
	return u
}

// SetSensitivity sets the "sensitivity" field.
func (u *EvidenceUpsert) SetSensitivity(v string) *EvidenceUpsert {
	u.Set(evidence.FieldSensitivity, v)
	return u
}

// UpdateSensitivity sets the "sensitivity" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateSensitivity() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldSensitivity)
	return u
}

// ClearSensitivity clears the value of the "sensitivity" field.
func (u *EvidenceUpsert) ClearSensitivity() *EvidenceUpsert {
	u.SetNull(evidence.FieldSensitivity)
	return u
}

// SetCapturedBy sets the "captured_by" field.
func (u *EvidenceUpsert) SetCapturedBy(v string) *EvidenceUpsert {
	u.Set(evidence.FieldCapturedBy, v)
	return u
}

// UpdateCapturedBy sets the "captured_by" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateCapturedBy() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldCapturedBy)
	return u
}

// ClearCapturedBy clears the value of the "captured_by" field.
func (u *EvidenceUpsert) ClearCapturedBy() *EvidenceUpsert {
	u.SetNull(evidence.FieldCapturedBy)
	return u
}

// SetCapturedAt sets the "captured_at" field.
func (u *EvidenceUpsert) SetCapturedAt(v time.Time) *EvidenceUpsert {
	u.Set(evidence.FieldCapturedAt, v)
	return u
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateCapturedAt() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldCapturedAt)
	return u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *EvidenceUpsert) ClearCapturedAt() *EvidenceUpsert {
	u.SetNull(evidence.FieldCapturedAt)
	return u
}

// SetSourceURI sets the "source_uri" field.
func (u *EvidenceUpsert) SetSourceURI(v string) *EvidenceUpsert {
	u.Set(evidence.FieldSourceURI, v)
	return u
}

// UpdateSourceURI sets the "source_uri" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateSourceURI() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldSourceURI)
	return u
}

// ClearSourceURI clears the value of the "source_uri" field.
func (u *EvidenceUpsert) ClearSourceURI() *EvidenceUpsert {
	u.SetNull(evidence.FieldSourceURI)
	return u
}

// SetVerified sets the "verified" field.
func (u *EvidenceUpsert) SetVerified(v bool) *EvidenceUpsert {
	u.Set(evidence.FieldVerified, v)
	return u
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateVerified() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldVerified)
	return u
}

// SetCanonical sets the "canonical" field.
func (u *EvidenceUpsert) SetCanonical(v assessment.Evidence) *EvidenceUpsert {
	u.Set(evidence.FieldCanonical, v)
	return u
}

// UpdateCanonical sets the "canonical" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateCanonical() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldCanonical)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvidenceUpsert) SetUpdatedAt(v time.Time) *EvidenceUpsert {
	u.Set(evidence.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvidenceUpsert) UpdateUpdatedAt() *EvidenceUpsert {
	u.SetExcluded(evidence.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Evidence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evidence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvidenceUpsertOne) UpdateNewValues() *EvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(evidence.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(evidence.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Evidence.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EvidenceUpsertOne) Ignore() *EvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvidenceUpsertOne) DoNothing() *EvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvidenceCreate.OnConflict
// documentation for more info.
func (u *EvidenceUpsertOne) Update(set func(*EvidenceUpsert)) *EvidenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvidenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetSystem sets the "system" field.
func (u *EvidenceUpsertOne) SetSystem(v string) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateSystem() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSystem()
	})
}

// ClearSystem clears the value of the "system" field.
func (u *EvidenceUpsertOne) ClearSystem() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSystem()
	})
}

// SetSensitivity sets the "sensitivity" field.
func (u *EvidenceUpsertOne) SetSensitivity(v string) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSensitivity(v)
	})
}

// UpdateSensitivity sets the "sensitivity" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateSensitivity() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSensitivity()
	})
}

// ClearSensitivity clears the value of the "sensitivity" field.
func (u *EvidenceUpsertOne) ClearSensitivity() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSensitivity()
	})
}

// SetCapturedBy sets the "captured_by" field.
func (u *EvidenceUpsertOne) SetCapturedBy(v string) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCapturedBy(v)
	})
}

// UpdateCapturedBy sets the "captured_by" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateCapturedBy() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCapturedBy()
	})
}

// ClearCapturedBy clears the value of the "captured_by" field.
func (u *EvidenceUpsertOne) ClearCapturedBy() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearCapturedBy()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *EvidenceUpsertOne) SetCapturedAt(v time.Time) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateCapturedAt() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *EvidenceUpsertOne) ClearCapturedAt() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearCapturedAt()
	})
}

// SetSourceURI sets the "source_uri" field.
func (u *EvidenceUpsertOne) SetSourceURI(v string) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSourceURI(v)
	})
}

// UpdateSourceURI sets the "source_uri" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateSourceURI() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSourceURI()
	})
}

// ClearSourceURI clears the value of the "source_uri" field.
func (u *EvidenceUpsertOne) ClearSourceURI() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSourceURI()
	})
}

// SetVerified sets the "verified" field.
func (u *EvidenceUpsertOne) SetVerified(v bool) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateVerified() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateVerified()
	})
}

// SetCanonical sets the "canonical" field.
func (u *EvidenceUpsertOne) SetCanonical(v assessment.Evidence) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCanonical(v)
	})
}

// UpdateCanonical sets the "canonical" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateCanonical() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCanonical()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvidenceUpsertOne) SetUpdatedAt(v time.Time) *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvidenceUpsertOne) UpdateUpdatedAt() *EvidenceUpsertOne {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvidenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvidenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvidenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EvidenceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EvidenceUpsertOne.ID is not supported by MySQL driver. Use EvidenceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EvidenceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EvidenceCreateBulk is the builder for creating many Evidence entities in bulk.
type EvidenceCreateBulk struct {
	config
	err      error
	builders []*EvidenceCreate
	conflict []sql.ConflictOption
}

// Save creates the Evidence entities in the database.
func (_c *EvidenceCreateBulk) Save(ctx context.Context) ([]*Evidence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Evidence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EvidenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EvidenceCreateBulk) SaveX(ctx context.Context) []*Evidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvidenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvidenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Evidence.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EvidenceUpsert) {
//			SetSystem(v+v).
//		}).
//		Exec(ctx)
func (_c *EvidenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *EvidenceUpsertBulk {
	_c.conflict = opts
	return &EvidenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Evidence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EvidenceCreateBulk) OnConflictColumns(columns ...string) *EvidenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EvidenceUpsertBulk{
		create: _c,
	}
}

// EvidenceUpsertBulk is the builder for "upsert"-ing
// a bulk of Evidence nodes.
type EvidenceUpsertBulk struct {
	create *EvidenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Evidence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(evidence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EvidenceUpsertBulk) UpdateNewValues() *EvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(evidence.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(evidence.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Evidence.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EvidenceUpsertBulk) Ignore() *EvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EvidenceUpsertBulk) DoNothing() *EvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EvidenceCreateBulk.OnConflict
// documentation for more info.
func (u *EvidenceUpsertBulk) Update(set func(*EvidenceUpsert)) *EvidenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EvidenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetSystem sets the "system" field.
func (u *EvidenceUpsertBulk) SetSystem(v string) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateSystem() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSystem()
	})
}

// ClearSystem clears the value of the "system" field.
func (u *EvidenceUpsertBulk) ClearSystem() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSystem()
	})
}

// SetSensitivity sets the "sensitivity" field.
func (u *EvidenceUpsertBulk) SetSensitivity(v string) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSensitivity(v)
	})
}

// UpdateSensitivity sets the "sensitivity" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateSensitivity() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSensitivity()
	})
}

// ClearSensitivity clears the value of the "sensitivity" field.
func (u *EvidenceUpsertBulk) ClearSensitivity() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSensitivity()
	})
}

// SetCapturedBy sets the "captured_by" field.
func (u *EvidenceUpsertBulk) SetCapturedBy(v string) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCapturedBy(v)
	})
}

// UpdateCapturedBy sets the "captured_by" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateCapturedBy() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCapturedBy()
	})
}

// ClearCapturedBy clears the value of the "captured_by" field.
func (u *EvidenceUpsertBulk) ClearCapturedBy() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearCapturedBy()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *EvidenceUpsertBulk) SetCapturedAt(v time.Time) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateCapturedAt() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *EvidenceUpsertBulk) ClearCapturedAt() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearCapturedAt()
	})
}

// SetSourceURI sets the "source_uri" field.
func (u *EvidenceUpsertBulk) SetSourceURI(v string) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetSourceURI(v)
	})
}

// UpdateSourceURI sets the "source_uri" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateSourceURI() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateSourceURI()
	})
}

// ClearSourceURI clears the value of the "source_uri" field.
func (u *EvidenceUpsertBulk) ClearSourceURI() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.ClearSourceURI()
	})
}

// SetVerified sets the "verified" field.
func (u *EvidenceUpsertBulk) SetVerified(v bool) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetVerified(v)
	})
}

// UpdateVerified sets the "verified" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateVerified() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateVerified()
	})
}

// SetCanonical sets the "canonical" field.
func (u *EvidenceUpsertBulk) SetCanonical(v assessment.Evidence) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetCanonical(v)
	})
}

// UpdateCanonical sets the "canonical" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateCanonical() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateCanonical()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EvidenceUpsertBulk) SetUpdatedAt(v time.Time) *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EvidenceUpsertBulk) UpdateUpdatedAt() *EvidenceUpsertBulk {
	return u.Update(func(s *EvidenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EvidenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EvidenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EvidenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EvidenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
