// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniroadmap/ent/itemaugment"
)

// ItemAugment is the model entity for the ItemAugment schema.
type ItemAugment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// SourceRef holds the value of the "source_ref" field.
	SourceRef string `json:"source_ref,omitempty"`
	// Moscow holds the value of the "moscow" field.
	Moscow string `json:"moscow,omitempty"`
	// Kano holds the value of the "kano" field.
	Kano string `json:"kano,omitempty"`
	// Rice holds the value of the "rice" field.
	Rice map[string]float64 `json:"rice,omitempty"`
	// OkrRefs holds the value of the "okr_refs" field.
	OkrRefs []string `json:"okr_refs,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ItemAugment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case itemaugment.FieldRice, itemaugment.FieldOkrRefs, itemaugment.FieldMetadata:
			values[i] = new([]byte)
		case itemaugment.FieldID, itemaugment.FieldProvider, itemaugment.FieldSourceRef, itemaugment.FieldMoscow, itemaugment.FieldKano, itemaugment.FieldNotes:
			values[i] = new(sql.NullString)
		case itemaugment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ItemAugment fields.
func (_m *ItemAugment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case itemaugment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case itemaugment.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case itemaugment.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = value.String
			}
		case itemaugment.FieldMoscow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field moscow", values[i])
			} else if value.Valid {
				_m.Moscow = value.String
			}
		case itemaugment.FieldKano:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kano", values[i])
			} else if value.Valid {
				_m.Kano = value.String
			}
		case itemaugment.FieldRice:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rice", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Rice); err != nil {
					return fmt.Errorf("unmarshal field rice: %w", err)
				}
			}
		case itemaugment.FieldOkrRefs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field okr_refs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OkrRefs); err != nil {
					return fmt.Errorf("unmarshal field okr_refs: %w", err)
				}
			}
		case itemaugment.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case itemaugment.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case itemaugment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ItemAugment.
// This includes values selected through modifiers, order, etc.
func (_m *ItemAugment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ItemAugment.
// Note that you need to call ItemAugment.Unwrap() before calling this method if this ItemAugment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ItemAugment) Update() *ItemAugmentUpdateOne {
	return NewItemAugmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ItemAugment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ItemAugment) Unwrap() *ItemAugment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ItemAugment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ItemAugment) String() string {
	var builder strings.Builder
	builder.WriteString("ItemAugment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("source_ref=")
	builder.WriteString(_m.SourceRef)
	builder.WriteString(", ")
	builder.WriteString("moscow=")
	builder.WriteString(_m.Moscow)
	builder.WriteString(", ")
	builder.WriteString("kano=")
	builder.WriteString(_m.Kano)
	builder.WriteString(", ")
	builder.WriteString("rice=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rice))
	builder.WriteString(", ")
	builder.WriteString("okr_refs=")
	builder.WriteString(fmt.Sprintf("%v", _m.OkrRefs))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ItemAugments is a parsable slice of ItemAugment.
type ItemAugments []*ItemAugment
