// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/opportunityassessment"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// OpportunityAssessmentDelete is the builder for deleting a OpportunityAssessment entity.
type OpportunityAssessmentDelete struct {
	config
	hooks    []Hook
	mutation *OpportunityAssessmentMutation
}

// Where appends a list predicates to the OpportunityAssessmentDelete builder.
func (_d *OpportunityAssessmentDelete) Where(ps ...predicate.OpportunityAssessment) *OpportunityAssessmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpportunityAssessmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpportunityAssessmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpportunityAssessmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opportunityassessment.Table, sqlgraph.NewFieldSpec(opportunityassessment.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpportunityAssessmentDeleteOne is the builder for deleting a single OpportunityAssessment entity.
type OpportunityAssessmentDeleteOne struct {
	_d *OpportunityAssessmentDelete
}

// Where appends a list predicates to the OpportunityAssessmentDelete builder.
func (_d *OpportunityAssessmentDeleteOne) Where(ps ...predicate.OpportunityAssessment) *OpportunityAssessmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpportunityAssessmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opportunityassessment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpportunityAssessmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
