// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/portfoliodimension"
	"github.com/grokify/omniroadmap/ent/predicate"
)

// PortfolioDimensionDelete is the builder for deleting a PortfolioDimension entity.
type PortfolioDimensionDelete struct {
	config
	hooks    []Hook
	mutation *PortfolioDimensionMutation
}

// Where appends a list predicates to the PortfolioDimensionDelete builder.
func (_d *PortfolioDimensionDelete) Where(ps ...predicate.PortfolioDimension) *PortfolioDimensionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PortfolioDimensionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PortfolioDimensionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PortfolioDimensionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(portfoliodimension.Table, sqlgraph.NewFieldSpec(portfoliodimension.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PortfolioDimensionDeleteOne is the builder for deleting a single PortfolioDimension entity.
type PortfolioDimensionDeleteOne struct {
	_d *PortfolioDimensionDelete
}

// Where appends a list predicates to the PortfolioDimensionDelete builder.
func (_d *PortfolioDimensionDeleteOne) Where(ps ...predicate.PortfolioDimension) *PortfolioDimensionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PortfolioDimensionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{portfoliodimension.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PortfolioDimensionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
