// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/predicate"
	"github.com/grokify/omniroadmap/ent/profileassignment"
)

// ProfileAssignmentUpdate is the builder for updating ProfileAssignment entities.
type ProfileAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileAssignmentMutation
}

// Where appends a list predicates to the ProfileAssignmentUpdate builder.
func (_u *ProfileAssignmentUpdate) Where(ps ...predicate.ProfileAssignment) *ProfileAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *ProfileAssignmentUpdate) SetProfileID(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableProfileID(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetSecondary sets the "secondary" field.
func (_u *ProfileAssignmentUpdate) SetSecondary(v []string) *ProfileAssignmentUpdate {
	_u.mutation.SetSecondary(v)
	return _u
}

// AppendSecondary appends value to the "secondary" field.
func (_u *ProfileAssignmentUpdate) AppendSecondary(v []string) *ProfileAssignmentUpdate {
	_u.mutation.AppendSecondary(v)
	return _u
}

// ClearSecondary clears the value of the "secondary" field.
func (_u *ProfileAssignmentUpdate) ClearSecondary() *ProfileAssignmentUpdate {
	_u.mutation.ClearSecondary()
	return _u
}

// SetRationale sets the "rationale" field.
func (_u *ProfileAssignmentUpdate) SetRationale(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetRationale(v)
	return _u
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableRationale(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetRationale(*v)
	}
	return _u
}

// SetProposedBy sets the "proposed_by" field.
func (_u *ProfileAssignmentUpdate) SetProposedBy(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetProposedBy(v)
	return _u
}

// SetNillableProposedBy sets the "proposed_by" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableProposedBy(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetProposedBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProfileAssignmentUpdate) SetStatus(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableStatus(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *ProfileAssignmentUpdate) SetConfirmedBy(v string) *ProfileAssignmentUpdate {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableConfirmedBy(v *string) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *ProfileAssignmentUpdate) ClearConfirmedBy() *ProfileAssignmentUpdate {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ProfileAssignmentUpdate) SetConfirmedAt(v time.Time) *ProfileAssignmentUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ProfileAssignmentUpdate) SetNillableConfirmedAt(v *time.Time) *ProfileAssignmentUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ProfileAssignmentUpdate) ClearConfirmedAt() *ProfileAssignmentUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetEvidenceIds sets the "evidence_ids" field.
func (_u *ProfileAssignmentUpdate) SetEvidenceIds(v []string) *ProfileAssignmentUpdate {
	_u.mutation.SetEvidenceIds(v)
	return _u
}

// AppendEvidenceIds appends value to the "evidence_ids" field.
func (_u *ProfileAssignmentUpdate) AppendEvidenceIds(v []string) *ProfileAssignmentUpdate {
	_u.mutation.AppendEvidenceIds(v)
	return _u
}

// ClearEvidenceIds clears the value of the "evidence_ids" field.
func (_u *ProfileAssignmentUpdate) ClearEvidenceIds() *ProfileAssignmentUpdate {
	_u.mutation.ClearEvidenceIds()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProfileAssignmentUpdate) SetUpdatedAt(v time.Time) *ProfileAssignmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProfileAssignmentMutation object of the builder.
func (_u *ProfileAssignmentUpdate) Mutation() *ProfileAssignmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfileAssignmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfileAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileAssignmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := profileassignment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileAssignmentUpdate) check() error {
	if v, ok := _u.mutation.ProfileID(); ok {
		if err := profileassignment.ProfileIDValidator(v); err != nil {
			return &ValidationError{Name: "profile_id", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.profile_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rationale(); ok {
		if err := profileassignment.RationaleValidator(v); err != nil {
			return &ValidationError{Name: "rationale", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.rationale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProposedBy(); ok {
		if err := profileassignment.ProposedByValidator(v); err != nil {
			return &ValidationError{Name: "proposed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.proposed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := profileassignment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedBy(); ok {
		if err := profileassignment.ConfirmedByValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.confirmed_by": %w`, err)}
		}
	}
	return nil
}

func (_u *ProfileAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileassignment.Table, profileassignment.Columns, sqlgraph.NewFieldSpec(profileassignment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(profileassignment.FieldProfileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secondary(); ok {
		_spec.SetField(profileassignment.FieldSecondary, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSecondary(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profileassignment.FieldSecondary, value)
		})
	}
	if _u.mutation.SecondaryCleared() {
		_spec.ClearField(profileassignment.FieldSecondary, field.TypeJSON)
	}
	if value, ok := _u.mutation.Rationale(); ok {
		_spec.SetField(profileassignment.FieldRationale, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProposedBy(); ok {
		_spec.SetField(profileassignment.FieldProposedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(profileassignment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedBy(); ok {
		_spec.SetField(profileassignment.FieldConfirmedBy, field.TypeString, value)
	}
	if _u.mutation.ConfirmedByCleared() {
		_spec.ClearField(profileassignment.FieldConfirmedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(profileassignment.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(profileassignment.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EvidenceIds(); ok {
		_spec.SetField(profileassignment.FieldEvidenceIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvidenceIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profileassignment.FieldEvidenceIds, value)
		})
	}
	if _u.mutation.EvidenceIdsCleared() {
		_spec.ClearField(profileassignment.FieldEvidenceIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(profileassignment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfileAssignmentUpdateOne is the builder for updating a single ProfileAssignment entity.
type ProfileAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileAssignmentMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *ProfileAssignmentUpdateOne) SetProfileID(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableProfileID(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetSecondary sets the "secondary" field.
func (_u *ProfileAssignmentUpdateOne) SetSecondary(v []string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetSecondary(v)
	return _u
}

// AppendSecondary appends value to the "secondary" field.
func (_u *ProfileAssignmentUpdateOne) AppendSecondary(v []string) *ProfileAssignmentUpdateOne {
	_u.mutation.AppendSecondary(v)
	return _u
}

// ClearSecondary clears the value of the "secondary" field.
func (_u *ProfileAssignmentUpdateOne) ClearSecondary() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearSecondary()
	return _u
}

// SetRationale sets the "rationale" field.
func (_u *ProfileAssignmentUpdateOne) SetRationale(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetRationale(v)
	return _u
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableRationale(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetRationale(*v)
	}
	return _u
}

// SetProposedBy sets the "proposed_by" field.
func (_u *ProfileAssignmentUpdateOne) SetProposedBy(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetProposedBy(v)
	return _u
}

// SetNillableProposedBy sets the "proposed_by" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableProposedBy(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetProposedBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProfileAssignmentUpdateOne) SetStatus(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableStatus(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *ProfileAssignmentUpdateOne) SetConfirmedBy(v string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableConfirmedBy(v *string) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *ProfileAssignmentUpdateOne) ClearConfirmedBy() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ProfileAssignmentUpdateOne) SetConfirmedAt(v time.Time) *ProfileAssignmentUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ProfileAssignmentUpdateOne) SetNillableConfirmedAt(v *time.Time) *ProfileAssignmentUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ProfileAssignmentUpdateOne) ClearConfirmedAt() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetEvidenceIds sets the "evidence_ids" field.
func (_u *ProfileAssignmentUpdateOne) SetEvidenceIds(v []string) *ProfileAssignmentUpdateOne {
	_u.mutation.SetEvidenceIds(v)
	return _u
}

// AppendEvidenceIds appends value to the "evidence_ids" field.
func (_u *ProfileAssignmentUpdateOne) AppendEvidenceIds(v []string) *ProfileAssignmentUpdateOne {
	_u.mutation.AppendEvidenceIds(v)
	return _u
}

// ClearEvidenceIds clears the value of the "evidence_ids" field.
func (_u *ProfileAssignmentUpdateOne) ClearEvidenceIds() *ProfileAssignmentUpdateOne {
	_u.mutation.ClearEvidenceIds()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProfileAssignmentUpdateOne) SetUpdatedAt(v time.Time) *ProfileAssignmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProfileAssignmentMutation object of the builder.
func (_u *ProfileAssignmentUpdateOne) Mutation() *ProfileAssignmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProfileAssignmentUpdate builder.
func (_u *ProfileAssignmentUpdateOne) Where(ps ...predicate.ProfileAssignment) *ProfileAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfileAssignmentUpdateOne) Select(field string, fields ...string) *ProfileAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProfileAssignment entity.
func (_u *ProfileAssignmentUpdateOne) Save(ctx context.Context) (*ProfileAssignment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileAssignmentUpdateOne) SaveX(ctx context.Context) *ProfileAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfileAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileAssignmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := profileassignment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProfileAssignmentUpdateOne) check() error {
	if v, ok := _u.mutation.ProfileID(); ok {
		if err := profileassignment.ProfileIDValidator(v); err != nil {
			return &ValidationError{Name: "profile_id", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.profile_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rationale(); ok {
		if err := profileassignment.RationaleValidator(v); err != nil {
			return &ValidationError{Name: "rationale", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.rationale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProposedBy(); ok {
		if err := profileassignment.ProposedByValidator(v); err != nil {
			return &ValidationError{Name: "proposed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.proposed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := profileassignment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedBy(); ok {
		if err := profileassignment.ConfirmedByValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.confirmed_by": %w`, err)}
		}
	}
	return nil
}

func (_u *ProfileAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *ProfileAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profileassignment.Table, profileassignment.Columns, sqlgraph.NewFieldSpec(profileassignment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfileAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileassignment.FieldID)
		for _, f := range fields {
			if !profileassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profileassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(profileassignment.FieldProfileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secondary(); ok {
		_spec.SetField(profileassignment.FieldSecondary, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSecondary(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profileassignment.FieldSecondary, value)
		})
	}
	if _u.mutation.SecondaryCleared() {
		_spec.ClearField(profileassignment.FieldSecondary, field.TypeJSON)
	}
	if value, ok := _u.mutation.Rationale(); ok {
		_spec.SetField(profileassignment.FieldRationale, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProposedBy(); ok {
		_spec.SetField(profileassignment.FieldProposedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(profileassignment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedBy(); ok {
		_spec.SetField(profileassignment.FieldConfirmedBy, field.TypeString, value)
	}
	if _u.mutation.ConfirmedByCleared() {
		_spec.ClearField(profileassignment.FieldConfirmedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(profileassignment.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(profileassignment.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EvidenceIds(); ok {
		_spec.SetField(profileassignment.FieldEvidenceIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvidenceIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, profileassignment.FieldEvidenceIds, value)
		})
	}
	if _u.mutation.EvidenceIdsCleared() {
		_spec.ClearField(profileassignment.FieldEvidenceIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(profileassignment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProfileAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
