// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniroadmap/ent/profileassignment"
)

// ProfileAssignmentCreate is the builder for creating a ProfileAssignment entity.
type ProfileAssignmentCreate struct {
	config
	mutation *ProfileAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProfileID sets the "profile_id" field.
func (_c *ProfileAssignmentCreate) SetProfileID(v string) *ProfileAssignmentCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetSecondary sets the "secondary" field.
func (_c *ProfileAssignmentCreate) SetSecondary(v []string) *ProfileAssignmentCreate {
	_c.mutation.SetSecondary(v)
	return _c
}

// SetRationale sets the "rationale" field.
func (_c *ProfileAssignmentCreate) SetRationale(v string) *ProfileAssignmentCreate {
	_c.mutation.SetRationale(v)
	return _c
}

// SetProposedBy sets the "proposed_by" field.
func (_c *ProfileAssignmentCreate) SetProposedBy(v string) *ProfileAssignmentCreate {
	_c.mutation.SetProposedBy(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProfileAssignmentCreate) SetStatus(v string) *ProfileAssignmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_c *ProfileAssignmentCreate) SetConfirmedBy(v string) *ProfileAssignmentCreate {
	_c.mutation.SetConfirmedBy(v)
	return _c
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_c *ProfileAssignmentCreate) SetNillableConfirmedBy(v *string) *ProfileAssignmentCreate {
	if v != nil {
		_c.SetConfirmedBy(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *ProfileAssignmentCreate) SetConfirmedAt(v time.Time) *ProfileAssignmentCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *ProfileAssignmentCreate) SetNillableConfirmedAt(v *time.Time) *ProfileAssignmentCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetEvidenceIds sets the "evidence_ids" field.
func (_c *ProfileAssignmentCreate) SetEvidenceIds(v []string) *ProfileAssignmentCreate {
	_c.mutation.SetEvidenceIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProfileAssignmentCreate) SetCreatedAt(v time.Time) *ProfileAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProfileAssignmentCreate) SetNillableCreatedAt(v *time.Time) *ProfileAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProfileAssignmentCreate) SetUpdatedAt(v time.Time) *ProfileAssignmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProfileAssignmentCreate) SetNillableUpdatedAt(v *time.Time) *ProfileAssignmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProfileAssignmentCreate) SetID(v string) *ProfileAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProfileAssignmentMutation object of the builder.
func (_c *ProfileAssignmentCreate) Mutation() *ProfileAssignmentMutation {
	return _c.mutation
}

// Save creates the ProfileAssignment in the database.
func (_c *ProfileAssignmentCreate) Save(ctx context.Context) (*ProfileAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfileAssignmentCreate) SaveX(ctx context.Context) *ProfileAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfileAssignmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := profileassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := profileassignment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfileAssignmentCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "ProfileAssignment.profile_id"`)}
	}
	if v, ok := _c.mutation.ProfileID(); ok {
		if err := profileassignment.ProfileIDValidator(v); err != nil {
			return &ValidationError{Name: "profile_id", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.profile_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rationale(); !ok {
		return &ValidationError{Name: "rationale", err: errors.New(`ent: missing required field "ProfileAssignment.rationale"`)}
	}
	if v, ok := _c.mutation.Rationale(); ok {
		if err := profileassignment.RationaleValidator(v); err != nil {
			return &ValidationError{Name: "rationale", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.rationale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProposedBy(); !ok {
		return &ValidationError{Name: "proposed_by", err: errors.New(`ent: missing required field "ProfileAssignment.proposed_by"`)}
	}
	if v, ok := _c.mutation.ProposedBy(); ok {
		if err := profileassignment.ProposedByValidator(v); err != nil {
			return &ValidationError{Name: "proposed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.proposed_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProfileAssignment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := profileassignment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ConfirmedBy(); ok {
		if err := profileassignment.ConfirmedByValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_by", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.confirmed_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProfileAssignment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProfileAssignment.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := profileassignment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProfileAssignment.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProfileAssignmentCreate) sqlSave(ctx context.Context) (*ProfileAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProfileAssignment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfileAssignmentCreate) createSpec() (*ProfileAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &ProfileAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profileassignment.Table, sqlgraph.NewFieldSpec(profileassignment.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(profileassignment.FieldProfileID, field.TypeString, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.Secondary(); ok {
		_spec.SetField(profileassignment.FieldSecondary, field.TypeJSON, value)
		_node.Secondary = value
	}
	if value, ok := _c.mutation.Rationale(); ok {
		_spec.SetField(profileassignment.FieldRationale, field.TypeString, value)
		_node.Rationale = value
	}
	if value, ok := _c.mutation.ProposedBy(); ok {
		_spec.SetField(profileassignment.FieldProposedBy, field.TypeString, value)
		_node.ProposedBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(profileassignment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ConfirmedBy(); ok {
		_spec.SetField(profileassignment.FieldConfirmedBy, field.TypeString, value)
		_node.ConfirmedBy = value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(profileassignment.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.EvidenceIds(); ok {
		_spec.SetField(profileassignment.FieldEvidenceIds, field.TypeJSON, value)
		_node.EvidenceIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(profileassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(profileassignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProfileAssignment.Create().
//		SetProfileID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProfileAssignmentUpsert) {
//			SetProfileID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProfileAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *ProfileAssignmentUpsertOne {
	_c.conflict = opts
	return &ProfileAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProfileAssignmentCreate) OnConflictColumns(columns ...string) *ProfileAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProfileAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// ProfileAssignmentUpsertOne is the builder for "upsert"-ing
	//  one ProfileAssignment node.
	ProfileAssignmentUpsertOne struct {
		create *ProfileAssignmentCreate
	}

	// ProfileAssignmentUpsert is the "OnConflict" setter.
	ProfileAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetProfileID sets the "profile_id" field.
func (u *ProfileAssignmentUpsert) SetProfileID(v string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldProfileID, v)
	return u
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateProfileID() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldProfileID)
	return u
}

// SetSecondary sets the "secondary" field.
func (u *ProfileAssignmentUpsert) SetSecondary(v []string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldSecondary, v)
	return u
}

// UpdateSecondary sets the "secondary" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateSecondary() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldSecondary)
	return u
}

// ClearSecondary clears the value of the "secondary" field.
func (u *ProfileAssignmentUpsert) ClearSecondary() *ProfileAssignmentUpsert {
	u.SetNull(profileassignment.FieldSecondary)
	return u
}

// SetRationale sets the "rationale" field.
func (u *ProfileAssignmentUpsert) SetRationale(v string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldRationale, v)
	return u
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateRationale() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldRationale)
	return u
}

// SetProposedBy sets the "proposed_by" field.
func (u *ProfileAssignmentUpsert) SetProposedBy(v string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldProposedBy, v)
	return u
}

// UpdateProposedBy sets the "proposed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateProposedBy() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldProposedBy)
	return u
}

// SetStatus sets the "status" field.
func (u *ProfileAssignmentUpsert) SetStatus(v string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateStatus() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldStatus)
	return u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *ProfileAssignmentUpsert) SetConfirmedBy(v string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldConfirmedBy, v)
	return u
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateConfirmedBy() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldConfirmedBy)
	return u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *ProfileAssignmentUpsert) ClearConfirmedBy() *ProfileAssignmentUpsert {
	u.SetNull(profileassignment.FieldConfirmedBy)
	return u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *ProfileAssignmentUpsert) SetConfirmedAt(v time.Time) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldConfirmedAt, v)
	return u
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateConfirmedAt() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldConfirmedAt)
	return u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *ProfileAssignmentUpsert) ClearConfirmedAt() *ProfileAssignmentUpsert {
	u.SetNull(profileassignment.FieldConfirmedAt)
	return u
}

// SetEvidenceIds sets the "evidence_ids" field.
func (u *ProfileAssignmentUpsert) SetEvidenceIds(v []string) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldEvidenceIds, v)
	return u
}

// UpdateEvidenceIds sets the "evidence_ids" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateEvidenceIds() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldEvidenceIds)
	return u
}

// ClearEvidenceIds clears the value of the "evidence_ids" field.
func (u *ProfileAssignmentUpsert) ClearEvidenceIds() *ProfileAssignmentUpsert {
	u.SetNull(profileassignment.FieldEvidenceIds)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProfileAssignmentUpsert) SetUpdatedAt(v time.Time) *ProfileAssignmentUpsert {
	u.Set(profileassignment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsert) UpdateUpdatedAt() *ProfileAssignmentUpsert {
	u.SetExcluded(profileassignment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(profileassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProfileAssignmentUpsertOne) UpdateNewValues() *ProfileAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(profileassignment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(profileassignment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProfileAssignmentUpsertOne) Ignore() *ProfileAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProfileAssignmentUpsertOne) DoNothing() *ProfileAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProfileAssignmentCreate.OnConflict
// documentation for more info.
func (u *ProfileAssignmentUpsertOne) Update(set func(*ProfileAssignmentUpsert)) *ProfileAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProfileAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetProfileID sets the "profile_id" field.
func (u *ProfileAssignmentUpsertOne) SetProfileID(v string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateProfileID() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateProfileID()
	})
}

// SetSecondary sets the "secondary" field.
func (u *ProfileAssignmentUpsertOne) SetSecondary(v []string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetSecondary(v)
	})
}

// UpdateSecondary sets the "secondary" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateSecondary() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateSecondary()
	})
}

// ClearSecondary clears the value of the "secondary" field.
func (u *ProfileAssignmentUpsertOne) ClearSecondary() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearSecondary()
	})
}

// SetRationale sets the "rationale" field.
func (u *ProfileAssignmentUpsertOne) SetRationale(v string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetRationale(v)
	})
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateRationale() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateRationale()
	})
}

// SetProposedBy sets the "proposed_by" field.
func (u *ProfileAssignmentUpsertOne) SetProposedBy(v string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetProposedBy(v)
	})
}

// UpdateProposedBy sets the "proposed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateProposedBy() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateProposedBy()
	})
}

// SetStatus sets the "status" field.
func (u *ProfileAssignmentUpsertOne) SetStatus(v string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateStatus() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateStatus()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *ProfileAssignmentUpsertOne) SetConfirmedBy(v string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateConfirmedBy() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *ProfileAssignmentUpsertOne) ClearConfirmedBy() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *ProfileAssignmentUpsertOne) SetConfirmedAt(v time.Time) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateConfirmedAt() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *ProfileAssignmentUpsertOne) ClearConfirmedAt() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetEvidenceIds sets the "evidence_ids" field.
func (u *ProfileAssignmentUpsertOne) SetEvidenceIds(v []string) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetEvidenceIds(v)
	})
}

// UpdateEvidenceIds sets the "evidence_ids" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateEvidenceIds() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateEvidenceIds()
	})
}

// ClearEvidenceIds clears the value of the "evidence_ids" field.
func (u *ProfileAssignmentUpsertOne) ClearEvidenceIds() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearEvidenceIds()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProfileAssignmentUpsertOne) SetUpdatedAt(v time.Time) *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertOne) UpdateUpdatedAt() *ProfileAssignmentUpsertOne {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProfileAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProfileAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProfileAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProfileAssignmentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProfileAssignmentUpsertOne.ID is not supported by MySQL driver. Use ProfileAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProfileAssignmentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProfileAssignmentCreateBulk is the builder for creating many ProfileAssignment entities in bulk.
type ProfileAssignmentCreateBulk struct {
	config
	err      error
	builders []*ProfileAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the ProfileAssignment entities in the database.
func (_c *ProfileAssignmentCreateBulk) Save(ctx context.Context) ([]*ProfileAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProfileAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfileAssignmentCreateBulk) SaveX(ctx context.Context) []*ProfileAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProfileAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProfileAssignmentUpsert) {
//			SetProfileID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProfileAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProfileAssignmentUpsertBulk {
	_c.conflict = opts
	return &ProfileAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProfileAssignmentCreateBulk) OnConflictColumns(columns ...string) *ProfileAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProfileAssignmentUpsertBulk{
		create: _c,
	}
}

// ProfileAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of ProfileAssignment nodes.
type ProfileAssignmentUpsertBulk struct {
	create *ProfileAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(profileassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProfileAssignmentUpsertBulk) UpdateNewValues() *ProfileAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(profileassignment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(profileassignment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProfileAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProfileAssignmentUpsertBulk) Ignore() *ProfileAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProfileAssignmentUpsertBulk) DoNothing() *ProfileAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProfileAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *ProfileAssignmentUpsertBulk) Update(set func(*ProfileAssignmentUpsert)) *ProfileAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProfileAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetProfileID sets the "profile_id" field.
func (u *ProfileAssignmentUpsertBulk) SetProfileID(v string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateProfileID() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateProfileID()
	})
}

// SetSecondary sets the "secondary" field.
func (u *ProfileAssignmentUpsertBulk) SetSecondary(v []string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetSecondary(v)
	})
}

// UpdateSecondary sets the "secondary" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateSecondary() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateSecondary()
	})
}

// ClearSecondary clears the value of the "secondary" field.
func (u *ProfileAssignmentUpsertBulk) ClearSecondary() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearSecondary()
	})
}

// SetRationale sets the "rationale" field.
func (u *ProfileAssignmentUpsertBulk) SetRationale(v string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetRationale(v)
	})
}

// UpdateRationale sets the "rationale" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateRationale() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateRationale()
	})
}

// SetProposedBy sets the "proposed_by" field.
func (u *ProfileAssignmentUpsertBulk) SetProposedBy(v string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetProposedBy(v)
	})
}

// UpdateProposedBy sets the "proposed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateProposedBy() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateProposedBy()
	})
}

// SetStatus sets the "status" field.
func (u *ProfileAssignmentUpsertBulk) SetStatus(v string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateStatus() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateStatus()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *ProfileAssignmentUpsertBulk) SetConfirmedBy(v string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateConfirmedBy() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *ProfileAssignmentUpsertBulk) ClearConfirmedBy() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *ProfileAssignmentUpsertBulk) SetConfirmedAt(v time.Time) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateConfirmedAt() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *ProfileAssignmentUpsertBulk) ClearConfirmedAt() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetEvidenceIds sets the "evidence_ids" field.
func (u *ProfileAssignmentUpsertBulk) SetEvidenceIds(v []string) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetEvidenceIds(v)
	})
}

// UpdateEvidenceIds sets the "evidence_ids" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateEvidenceIds() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateEvidenceIds()
	})
}

// ClearEvidenceIds clears the value of the "evidence_ids" field.
func (u *ProfileAssignmentUpsertBulk) ClearEvidenceIds() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.ClearEvidenceIds()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProfileAssignmentUpsertBulk) SetUpdatedAt(v time.Time) *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProfileAssignmentUpsertBulk) UpdateUpdatedAt() *ProfileAssignmentUpsertBulk {
	return u.Update(func(s *ProfileAssignmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProfileAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProfileAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProfileAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProfileAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
