// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/grokify/omniroadmap/ent/customfielddef"
	"github.com/grokify/omniroadmap/ent/dimensionoption"
	"github.com/grokify/omniroadmap/ent/evidence"
	"github.com/grokify/omniroadmap/ent/item"
	"github.com/grokify/omniroadmap/ent/itemaugment"
	"github.com/grokify/omniroadmap/ent/opportunityassessment"
	"github.com/grokify/omniroadmap/ent/opportunityspec"
	"github.com/grokify/omniroadmap/ent/portfoliodimension"
	"github.com/grokify/omniroadmap/ent/rankoverride"
	"github.com/grokify/omniroadmap/ent/release"
	"github.com/grokify/omniroadmap/ent/reportdataset"
	"github.com/grokify/omniroadmap/ent/schema"
	"github.com/grokify/omniroadmap/ent/syncmeta"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customfielddefFields := schema.CustomFieldDef{}.Fields()
	_ = customfielddefFields
	// customfielddefDescProvider is the schema descriptor for provider field.
	customfielddefDescProvider := customfielddefFields[1].Descriptor()
	// customfielddef.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	customfielddef.ProviderValidator = func() func(string) error {
		validators := customfielddefDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// customfielddefDescKey is the schema descriptor for key field.
	customfielddefDescKey := customfielddefFields[2].Descriptor()
	// customfielddef.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	customfielddef.KeyValidator = func() func(string) error {
		validators := customfielddefDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// customfielddefDescName is the schema descriptor for name field.
	customfielddefDescName := customfielddefFields[3].Descriptor()
	// customfielddef.NameValidator is a validator for the "name" field. It is called by the builders before save.
	customfielddef.NameValidator = customfielddefDescName.Validators[0].(func(string) error)
	// customfielddefDescFieldType is the schema descriptor for field_type field.
	customfielddefDescFieldType := customfielddefFields[4].Descriptor()
	// customfielddef.FieldTypeValidator is a validator for the "field_type" field. It is called by the builders before save.
	customfielddef.FieldTypeValidator = customfielddefDescFieldType.Validators[0].(func(string) error)
	// customfielddefDescSyncedAt is the schema descriptor for synced_at field.
	customfielddefDescSyncedAt := customfielddefFields[7].Descriptor()
	// customfielddef.DefaultSyncedAt holds the default value on creation for the synced_at field.
	customfielddef.DefaultSyncedAt = customfielddefDescSyncedAt.Default.(func() time.Time)
	// customfielddefDescID is the schema descriptor for id field.
	customfielddefDescID := customfielddefFields[0].Descriptor()
	// customfielddef.IDValidator is a validator for the "id" field. It is called by the builders before save.
	customfielddef.IDValidator = func() func(string) error {
		validators := customfielddefDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	dimensionoptionFields := schema.DimensionOption{}.Fields()
	_ = dimensionoptionFields
	// dimensionoptionDescDimensionRowID is the schema descriptor for dimension_row_id field.
	dimensionoptionDescDimensionRowID := dimensionoptionFields[1].Descriptor()
	// dimensionoption.DimensionRowIDValidator is a validator for the "dimension_row_id" field. It is called by the builders before save.
	dimensionoption.DimensionRowIDValidator = func() func(string) error {
		validators := dimensionoptionDescDimensionRowID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dimension_row_id string) error {
			for _, fn := range fns {
				if err := fn(dimension_row_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dimensionoptionDescOptionID is the schema descriptor for option_id field.
	dimensionoptionDescOptionID := dimensionoptionFields[2].Descriptor()
	// dimensionoption.OptionIDValidator is a validator for the "option_id" field. It is called by the builders before save.
	dimensionoption.OptionIDValidator = func() func(string) error {
		validators := dimensionoptionDescOptionID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(option_id string) error {
			for _, fn := range fns {
				if err := fn(option_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dimensionoptionDescLabel is the schema descriptor for label field.
	dimensionoptionDescLabel := dimensionoptionFields[3].Descriptor()
	// dimensionoption.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	dimensionoption.LabelValidator = func() func(string) error {
		validators := dimensionoptionDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dimensionoptionDescSequence is the schema descriptor for sequence field.
	dimensionoptionDescSequence := dimensionoptionFields[5].Descriptor()
	// dimensionoption.DefaultSequence holds the default value on creation for the sequence field.
	dimensionoption.DefaultSequence = dimensionoptionDescSequence.Default.(int)
	// dimensionoptionDescID is the schema descriptor for id field.
	dimensionoptionDescID := dimensionoptionFields[0].Descriptor()
	// dimensionoption.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dimensionoption.IDValidator = func() func(string) error {
		validators := dimensionoptionDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	evidenceFields := schema.Evidence{}.Fields()
	_ = evidenceFields
	// evidenceDescSystem is the schema descriptor for system field.
	evidenceDescSystem := evidenceFields[1].Descriptor()
	// evidence.SystemValidator is a validator for the "system" field. It is called by the builders before save.
	evidence.SystemValidator = evidenceDescSystem.Validators[0].(func(string) error)
	// evidenceDescSensitivity is the schema descriptor for sensitivity field.
	evidenceDescSensitivity := evidenceFields[2].Descriptor()
	// evidence.SensitivityValidator is a validator for the "sensitivity" field. It is called by the builders before save.
	evidence.SensitivityValidator = evidenceDescSensitivity.Validators[0].(func(string) error)
	// evidenceDescCapturedBy is the schema descriptor for captured_by field.
	evidenceDescCapturedBy := evidenceFields[3].Descriptor()
	// evidence.CapturedByValidator is a validator for the "captured_by" field. It is called by the builders before save.
	evidence.CapturedByValidator = evidenceDescCapturedBy.Validators[0].(func(string) error)
	// evidenceDescSourceURI is the schema descriptor for source_uri field.
	evidenceDescSourceURI := evidenceFields[5].Descriptor()
	// evidence.SourceURIValidator is a validator for the "source_uri" field. It is called by the builders before save.
	evidence.SourceURIValidator = evidenceDescSourceURI.Validators[0].(func(string) error)
	// evidenceDescVerified is the schema descriptor for verified field.
	evidenceDescVerified := evidenceFields[6].Descriptor()
	// evidence.DefaultVerified holds the default value on creation for the verified field.
	evidence.DefaultVerified = evidenceDescVerified.Default.(bool)
	// evidenceDescCreatedAt is the schema descriptor for created_at field.
	evidenceDescCreatedAt := evidenceFields[8].Descriptor()
	// evidence.DefaultCreatedAt holds the default value on creation for the created_at field.
	evidence.DefaultCreatedAt = evidenceDescCreatedAt.Default.(func() time.Time)
	// evidenceDescUpdatedAt is the schema descriptor for updated_at field.
	evidenceDescUpdatedAt := evidenceFields[9].Descriptor()
	// evidence.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	evidence.DefaultUpdatedAt = evidenceDescUpdatedAt.Default.(func() time.Time)
	// evidence.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	evidence.UpdateDefaultUpdatedAt = evidenceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// evidenceDescID is the schema descriptor for id field.
	evidenceDescID := evidenceFields[0].Descriptor()
	// evidence.IDValidator is a validator for the "id" field. It is called by the builders before save.
	evidence.IDValidator = func() func(string) error {
		validators := evidenceDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescProvider is the schema descriptor for provider field.
	itemDescProvider := itemFields[1].Descriptor()
	// item.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	item.ProviderValidator = func() func(string) error {
		validators := itemDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescSourceID is the schema descriptor for source_id field.
	itemDescSourceID := itemFields[2].Descriptor()
	// item.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	item.SourceIDValidator = func() func(string) error {
		validators := itemDescSourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source_id string) error {
			for _, fn := range fns {
				if err := fn(source_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescSourceRef is the schema descriptor for source_ref field.
	itemDescSourceRef := itemFields[3].Descriptor()
	// item.SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	item.SourceRefValidator = itemDescSourceRef.Validators[0].(func(string) error)
	// itemDescSourceURL is the schema descriptor for source_url field.
	itemDescSourceURL := itemFields[4].Descriptor()
	// item.SourceURLValidator is a validator for the "source_url" field. It is called by the builders before save.
	item.SourceURLValidator = itemDescSourceURL.Validators[0].(func(string) error)
	// itemDescWorkspaceRef is the schema descriptor for workspace_ref field.
	itemDescWorkspaceRef := itemFields[5].Descriptor()
	// item.WorkspaceRefValidator is a validator for the "workspace_ref" field. It is called by the builders before save.
	item.WorkspaceRefValidator = itemDescWorkspaceRef.Validators[0].(func(string) error)
	// itemDescKind is the schema descriptor for kind field.
	itemDescKind := itemFields[6].Descriptor()
	// item.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	item.KindValidator = func() func(string) error {
		validators := itemDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemFields[7].Descriptor()
	// item.NameValidator is a validator for the "name" field. It is called by the builders before save.
	item.NameValidator = itemDescName.Validators[0].(func(string) error)
	// itemDescStatusID is the schema descriptor for status_id field.
	itemDescStatusID := itemFields[9].Descriptor()
	// item.StatusIDValidator is a validator for the "status_id" field. It is called by the builders before save.
	item.StatusIDValidator = itemDescStatusID.Validators[0].(func(string) error)
	// itemDescStatusName is the schema descriptor for status_name field.
	itemDescStatusName := itemFields[10].Descriptor()
	// item.StatusNameValidator is a validator for the "status_name" field. It is called by the builders before save.
	item.StatusNameValidator = itemDescStatusName.Validators[0].(func(string) error)
	// itemDescStatusCategory is the schema descriptor for status_category field.
	itemDescStatusCategory := itemFields[11].Descriptor()
	// item.StatusCategoryValidator is a validator for the "status_category" field. It is called by the builders before save.
	item.StatusCategoryValidator = itemDescStatusCategory.Validators[0].(func(string) error)
	// itemDescStatusComplete is the schema descriptor for status_complete field.
	itemDescStatusComplete := itemFields[12].Descriptor()
	// item.DefaultStatusComplete holds the default value on creation for the status_complete field.
	item.DefaultStatusComplete = itemDescStatusComplete.Default.(bool)
	// itemDescParentID is the schema descriptor for parent_id field.
	itemDescParentID := itemFields[14].Descriptor()
	// item.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	item.ParentIDValidator = itemDescParentID.Validators[0].(func(string) error)
	// itemDescReleaseID is the schema descriptor for release_id field.
	itemDescReleaseID := itemFields[15].Descriptor()
	// item.ReleaseIDValidator is a validator for the "release_id" field. It is called by the builders before save.
	item.ReleaseIDValidator = itemDescReleaseID.Validators[0].(func(string) error)
	// itemDescOwnerID is the schema descriptor for owner_id field.
	itemDescOwnerID := itemFields[20].Descriptor()
	// item.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	item.OwnerIDValidator = itemDescOwnerID.Validators[0].(func(string) error)
	// itemDescOwnerName is the schema descriptor for owner_name field.
	itemDescOwnerName := itemFields[21].Descriptor()
	// item.OwnerNameValidator is a validator for the "owner_name" field. It is called by the builders before save.
	item.OwnerNameValidator = itemDescOwnerName.Validators[0].(func(string) error)
	// itemDescOwnerEmail is the schema descriptor for owner_email field.
	itemDescOwnerEmail := itemFields[22].Descriptor()
	// item.OwnerEmailValidator is a validator for the "owner_email" field. It is called by the builders before save.
	item.OwnerEmailValidator = itemDescOwnerEmail.Validators[0].(func(string) error)
	// itemDescMoscow is the schema descriptor for moscow field.
	itemDescMoscow := itemFields[23].Descriptor()
	// item.MoscowValidator is a validator for the "moscow" field. It is called by the builders before save.
	item.MoscowValidator = itemDescMoscow.Validators[0].(func(string) error)
	// itemDescKano is the schema descriptor for kano field.
	itemDescKano := itemFields[24].Descriptor()
	// item.KanoValidator is a validator for the "kano" field. It is called by the builders before save.
	item.KanoValidator = itemDescKano.Validators[0].(func(string) error)
	// itemDescSyncedAt is the schema descriptor for synced_at field.
	itemDescSyncedAt := itemFields[29].Descriptor()
	// item.DefaultSyncedAt holds the default value on creation for the synced_at field.
	item.DefaultSyncedAt = itemDescSyncedAt.Default.(func() time.Time)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.IDValidator is a validator for the "id" field. It is called by the builders before save.
	item.IDValidator = func() func(string) error {
		validators := itemDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	itemaugmentFields := schema.ItemAugment{}.Fields()
	_ = itemaugmentFields
	// itemaugmentDescProvider is the schema descriptor for provider field.
	itemaugmentDescProvider := itemaugmentFields[1].Descriptor()
	// itemaugment.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	itemaugment.ProviderValidator = func() func(string) error {
		validators := itemaugmentDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemaugmentDescSourceRef is the schema descriptor for source_ref field.
	itemaugmentDescSourceRef := itemaugmentFields[2].Descriptor()
	// itemaugment.SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	itemaugment.SourceRefValidator = func() func(string) error {
		validators := itemaugmentDescSourceRef.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source_ref string) error {
			for _, fn := range fns {
				if err := fn(source_ref); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemaugmentDescMoscow is the schema descriptor for moscow field.
	itemaugmentDescMoscow := itemaugmentFields[3].Descriptor()
	// itemaugment.MoscowValidator is a validator for the "moscow" field. It is called by the builders before save.
	itemaugment.MoscowValidator = itemaugmentDescMoscow.Validators[0].(func(string) error)
	// itemaugmentDescKano is the schema descriptor for kano field.
	itemaugmentDescKano := itemaugmentFields[4].Descriptor()
	// itemaugment.KanoValidator is a validator for the "kano" field. It is called by the builders before save.
	itemaugment.KanoValidator = itemaugmentDescKano.Validators[0].(func(string) error)
	// itemaugmentDescUpdatedAt is the schema descriptor for updated_at field.
	itemaugmentDescUpdatedAt := itemaugmentFields[9].Descriptor()
	// itemaugment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	itemaugment.DefaultUpdatedAt = itemaugmentDescUpdatedAt.Default.(func() time.Time)
	// itemaugmentDescID is the schema descriptor for id field.
	itemaugmentDescID := itemaugmentFields[0].Descriptor()
	// itemaugment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	itemaugment.IDValidator = func() func(string) error {
		validators := itemaugmentDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	opportunityassessmentFields := schema.OpportunityAssessment{}.Fields()
	_ = opportunityassessmentFields
	// opportunityassessmentDescOpportunitySpecID is the schema descriptor for opportunity_spec_id field.
	opportunityassessmentDescOpportunitySpecID := opportunityassessmentFields[1].Descriptor()
	// opportunityassessment.OpportunitySpecIDValidator is a validator for the "opportunity_spec_id" field. It is called by the builders before save.
	opportunityassessment.OpportunitySpecIDValidator = func() func(string) error {
		validators := opportunityassessmentDescOpportunitySpecID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(opportunity_spec_id string) error {
			for _, fn := range fns {
				if err := fn(opportunity_spec_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// opportunityassessmentDescRmiID is the schema descriptor for rmi_id field.
	opportunityassessmentDescRmiID := opportunityassessmentFields[2].Descriptor()
	// opportunityassessment.RmiIDValidator is a validator for the "rmi_id" field. It is called by the builders before save.
	opportunityassessment.RmiIDValidator = opportunityassessmentDescRmiID.Validators[0].(func(string) error)
	// opportunityassessmentDescTitle is the schema descriptor for title field.
	opportunityassessmentDescTitle := opportunityassessmentFields[3].Descriptor()
	// opportunityassessment.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	opportunityassessment.TitleValidator = opportunityassessmentDescTitle.Validators[0].(func(string) error)
	// opportunityassessmentDescCycleNumber is the schema descriptor for cycle_number field.
	opportunityassessmentDescCycleNumber := opportunityassessmentFields[4].Descriptor()
	// opportunityassessment.DefaultCycleNumber holds the default value on creation for the cycle_number field.
	opportunityassessment.DefaultCycleNumber = opportunityassessmentDescCycleNumber.Default.(int)
	// opportunityassessmentDescSupersedesID is the schema descriptor for supersedes_id field.
	opportunityassessmentDescSupersedesID := opportunityassessmentFields[6].Descriptor()
	// opportunityassessment.SupersedesIDValidator is a validator for the "supersedes_id" field. It is called by the builders before save.
	opportunityassessment.SupersedesIDValidator = opportunityassessmentDescSupersedesID.Validators[0].(func(string) error)
	// opportunityassessmentDescCurrent is the schema descriptor for current field.
	opportunityassessmentDescCurrent := opportunityassessmentFields[7].Descriptor()
	// opportunityassessment.DefaultCurrent holds the default value on creation for the current field.
	opportunityassessment.DefaultCurrent = opportunityassessmentDescCurrent.Default.(bool)
	// opportunityassessmentDescMoscowClass is the schema descriptor for moscow_class field.
	opportunityassessmentDescMoscowClass := opportunityassessmentFields[8].Descriptor()
	// opportunityassessment.MoscowClassValidator is a validator for the "moscow_class" field. It is called by the builders before save.
	opportunityassessment.MoscowClassValidator = opportunityassessmentDescMoscowClass.Validators[0].(func(string) error)
	// opportunityassessmentDescRiceComputable is the schema descriptor for rice_computable field.
	opportunityassessmentDescRiceComputable := opportunityassessmentFields[10].Descriptor()
	// opportunityassessment.DefaultRiceComputable holds the default value on creation for the rice_computable field.
	opportunityassessment.DefaultRiceComputable = opportunityassessmentDescRiceComputable.Default.(bool)
	// opportunityassessmentDescKanoCategory is the schema descriptor for kano_category field.
	opportunityassessmentDescKanoCategory := opportunityassessmentFields[13].Descriptor()
	// opportunityassessment.KanoCategoryValidator is a validator for the "kano_category" field. It is called by the builders before save.
	opportunityassessment.KanoCategoryValidator = opportunityassessmentDescKanoCategory.Validators[0].(func(string) error)
	// opportunityassessmentDescMihCategory is the schema descriptor for mih_category field.
	opportunityassessmentDescMihCategory := opportunityassessmentFields[14].Descriptor()
	// opportunityassessment.MihCategoryValidator is a validator for the "mih_category" field. It is called by the builders before save.
	opportunityassessment.MihCategoryValidator = opportunityassessmentDescMihCategory.Validators[0].(func(string) error)
	// opportunityassessmentDescCreatedAt is the schema descriptor for created_at field.
	opportunityassessmentDescCreatedAt := opportunityassessmentFields[16].Descriptor()
	// opportunityassessment.DefaultCreatedAt holds the default value on creation for the created_at field.
	opportunityassessment.DefaultCreatedAt = opportunityassessmentDescCreatedAt.Default.(func() time.Time)
	// opportunityassessmentDescUpdatedAt is the schema descriptor for updated_at field.
	opportunityassessmentDescUpdatedAt := opportunityassessmentFields[17].Descriptor()
	// opportunityassessment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	opportunityassessment.DefaultUpdatedAt = opportunityassessmentDescUpdatedAt.Default.(func() time.Time)
	// opportunityassessment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	opportunityassessment.UpdateDefaultUpdatedAt = opportunityassessmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// opportunityassessmentDescID is the schema descriptor for id field.
	opportunityassessmentDescID := opportunityassessmentFields[0].Descriptor()
	// opportunityassessment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	opportunityassessment.IDValidator = func() func(string) error {
		validators := opportunityassessmentDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	opportunityspecFields := schema.OpportunitySpec{}.Fields()
	_ = opportunityspecFields
	// opportunityspecDescTitle is the schema descriptor for title field.
	opportunityspecDescTitle := opportunityspecFields[1].Descriptor()
	// opportunityspec.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	opportunityspec.TitleValidator = opportunityspecDescTitle.Validators[0].(func(string) error)
	// opportunityspecDescCreatedAt is the schema descriptor for created_at field.
	opportunityspecDescCreatedAt := opportunityspecFields[2].Descriptor()
	// opportunityspec.DefaultCreatedAt holds the default value on creation for the created_at field.
	opportunityspec.DefaultCreatedAt = opportunityspecDescCreatedAt.Default.(func() time.Time)
	// opportunityspecDescUpdatedAt is the schema descriptor for updated_at field.
	opportunityspecDescUpdatedAt := opportunityspecFields[3].Descriptor()
	// opportunityspec.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	opportunityspec.DefaultUpdatedAt = opportunityspecDescUpdatedAt.Default.(func() time.Time)
	// opportunityspec.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	opportunityspec.UpdateDefaultUpdatedAt = opportunityspecDescUpdatedAt.UpdateDefault.(func() time.Time)
	// opportunityspecDescID is the schema descriptor for id field.
	opportunityspecDescID := opportunityspecFields[0].Descriptor()
	// opportunityspec.IDValidator is a validator for the "id" field. It is called by the builders before save.
	opportunityspec.IDValidator = func() func(string) error {
		validators := opportunityspecDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	portfoliodimensionFields := schema.PortfolioDimension{}.Fields()
	_ = portfoliodimensionFields
	// portfoliodimensionDescDimensionID is the schema descriptor for dimension_id field.
	portfoliodimensionDescDimensionID := portfoliodimensionFields[1].Descriptor()
	// portfoliodimension.DimensionIDValidator is a validator for the "dimension_id" field. It is called by the builders before save.
	portfoliodimension.DimensionIDValidator = func() func(string) error {
		validators := portfoliodimensionDescDimensionID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dimension_id string) error {
			for _, fn := range fns {
				if err := fn(dimension_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// portfoliodimensionDescVersion is the schema descriptor for version field.
	portfoliodimensionDescVersion := portfoliodimensionFields[2].Descriptor()
	// portfoliodimension.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	portfoliodimension.VersionValidator = func() func(string) error {
		validators := portfoliodimensionDescVersion.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(version string) error {
			for _, fn := range fns {
				if err := fn(version); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// portfoliodimensionDescName is the schema descriptor for name field.
	portfoliodimensionDescName := portfoliodimensionFields[3].Descriptor()
	// portfoliodimension.NameValidator is a validator for the "name" field. It is called by the builders before save.
	portfoliodimension.NameValidator = func() func(string) error {
		validators := portfoliodimensionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// portfoliodimensionDescKind is the schema descriptor for kind field.
	portfoliodimensionDescKind := portfoliodimensionFields[4].Descriptor()
	// portfoliodimension.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	portfoliodimension.KindValidator = func() func(string) error {
		validators := portfoliodimensionDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// portfoliodimensionDescBuiltIn is the schema descriptor for built_in field.
	portfoliodimensionDescBuiltIn := portfoliodimensionFields[5].Descriptor()
	// portfoliodimension.DefaultBuiltIn holds the default value on creation for the built_in field.
	portfoliodimension.DefaultBuiltIn = portfoliodimensionDescBuiltIn.Default.(bool)
	// portfoliodimensionDescCreatedAt is the schema descriptor for created_at field.
	portfoliodimensionDescCreatedAt := portfoliodimensionFields[6].Descriptor()
	// portfoliodimension.DefaultCreatedAt holds the default value on creation for the created_at field.
	portfoliodimension.DefaultCreatedAt = portfoliodimensionDescCreatedAt.Default.(func() time.Time)
	// portfoliodimensionDescID is the schema descriptor for id field.
	portfoliodimensionDescID := portfoliodimensionFields[0].Descriptor()
	// portfoliodimension.IDValidator is a validator for the "id" field. It is called by the builders before save.
	portfoliodimension.IDValidator = func() func(string) error {
		validators := portfoliodimensionDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	rankoverrideFields := schema.RankOverride{}.Fields()
	_ = rankoverrideFields
	// rankoverrideDescRationale is the schema descriptor for rationale field.
	rankoverrideDescRationale := rankoverrideFields[2].Descriptor()
	// rankoverride.RationaleValidator is a validator for the "rationale" field. It is called by the builders before save.
	rankoverride.RationaleValidator = rankoverrideDescRationale.Validators[0].(func(string) error)
	// rankoverrideDescApprovedBy is the schema descriptor for approved_by field.
	rankoverrideDescApprovedBy := rankoverrideFields[3].Descriptor()
	// rankoverride.ApprovedByValidator is a validator for the "approved_by" field. It is called by the builders before save.
	rankoverride.ApprovedByValidator = func() func(string) error {
		validators := rankoverrideDescApprovedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(approved_by string) error {
			for _, fn := range fns {
				if err := fn(approved_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rankoverrideDescCreatedAt is the schema descriptor for created_at field.
	rankoverrideDescCreatedAt := rankoverrideFields[5].Descriptor()
	// rankoverride.DefaultCreatedAt holds the default value on creation for the created_at field.
	rankoverride.DefaultCreatedAt = rankoverrideDescCreatedAt.Default.(func() time.Time)
	// rankoverrideDescUpdatedAt is the schema descriptor for updated_at field.
	rankoverrideDescUpdatedAt := rankoverrideFields[6].Descriptor()
	// rankoverride.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rankoverride.DefaultUpdatedAt = rankoverrideDescUpdatedAt.Default.(func() time.Time)
	// rankoverride.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rankoverride.UpdateDefaultUpdatedAt = rankoverrideDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rankoverrideDescID is the schema descriptor for id field.
	rankoverrideDescID := rankoverrideFields[0].Descriptor()
	// rankoverride.IDValidator is a validator for the "id" field. It is called by the builders before save.
	rankoverride.IDValidator = func() func(string) error {
		validators := rankoverrideDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	releaseFields := schema.Release{}.Fields()
	_ = releaseFields
	// releaseDescProvider is the schema descriptor for provider field.
	releaseDescProvider := releaseFields[1].Descriptor()
	// release.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	release.ProviderValidator = func() func(string) error {
		validators := releaseDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// releaseDescSourceID is the schema descriptor for source_id field.
	releaseDescSourceID := releaseFields[2].Descriptor()
	// release.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	release.SourceIDValidator = func() func(string) error {
		validators := releaseDescSourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source_id string) error {
			for _, fn := range fns {
				if err := fn(source_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// releaseDescSourceRef is the schema descriptor for source_ref field.
	releaseDescSourceRef := releaseFields[3].Descriptor()
	// release.SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	release.SourceRefValidator = releaseDescSourceRef.Validators[0].(func(string) error)
	// releaseDescSourceURL is the schema descriptor for source_url field.
	releaseDescSourceURL := releaseFields[4].Descriptor()
	// release.SourceURLValidator is a validator for the "source_url" field. It is called by the builders before save.
	release.SourceURLValidator = releaseDescSourceURL.Validators[0].(func(string) error)
	// releaseDescName is the schema descriptor for name field.
	releaseDescName := releaseFields[5].Descriptor()
	// release.NameValidator is a validator for the "name" field. It is called by the builders before save.
	release.NameValidator = releaseDescName.Validators[0].(func(string) error)
	// releaseDescReleased is the schema descriptor for released field.
	releaseDescReleased := releaseFields[8].Descriptor()
	// release.DefaultReleased holds the default value on creation for the released field.
	release.DefaultReleased = releaseDescReleased.Default.(bool)
	// releaseDescStatusID is the schema descriptor for status_id field.
	releaseDescStatusID := releaseFields[9].Descriptor()
	// release.StatusIDValidator is a validator for the "status_id" field. It is called by the builders before save.
	release.StatusIDValidator = releaseDescStatusID.Validators[0].(func(string) error)
	// releaseDescStatusName is the schema descriptor for status_name field.
	releaseDescStatusName := releaseFields[10].Descriptor()
	// release.StatusNameValidator is a validator for the "status_name" field. It is called by the builders before save.
	release.StatusNameValidator = releaseDescStatusName.Validators[0].(func(string) error)
	// releaseDescStatusCategory is the schema descriptor for status_category field.
	releaseDescStatusCategory := releaseFields[11].Descriptor()
	// release.StatusCategoryValidator is a validator for the "status_category" field. It is called by the builders before save.
	release.StatusCategoryValidator = releaseDescStatusCategory.Validators[0].(func(string) error)
	// releaseDescSyncedAt is the schema descriptor for synced_at field.
	releaseDescSyncedAt := releaseFields[14].Descriptor()
	// release.DefaultSyncedAt holds the default value on creation for the synced_at field.
	release.DefaultSyncedAt = releaseDescSyncedAt.Default.(func() time.Time)
	// releaseDescID is the schema descriptor for id field.
	releaseDescID := releaseFields[0].Descriptor()
	// release.IDValidator is a validator for the "id" field. It is called by the builders before save.
	release.IDValidator = func() func(string) error {
		validators := releaseDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	reportdatasetFields := schema.ReportDataset{}.Fields()
	_ = reportdatasetFields
	// reportdatasetDescRankingPolicyID is the schema descriptor for ranking_policy_id field.
	reportdatasetDescRankingPolicyID := reportdatasetFields[2].Descriptor()
	// reportdataset.RankingPolicyIDValidator is a validator for the "ranking_policy_id" field. It is called by the builders before save.
	reportdataset.RankingPolicyIDValidator = func() func(string) error {
		validators := reportdatasetDescRankingPolicyID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ranking_policy_id string) error {
			for _, fn := range fns {
				if err := fn(ranking_policy_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reportdatasetDescRankingPolicyVersion is the schema descriptor for ranking_policy_version field.
	reportdatasetDescRankingPolicyVersion := reportdatasetFields[3].Descriptor()
	// reportdataset.RankingPolicyVersionValidator is a validator for the "ranking_policy_version" field. It is called by the builders before save.
	reportdataset.RankingPolicyVersionValidator = func() func(string) error {
		validators := reportdatasetDescRankingPolicyVersion.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ranking_policy_version string) error {
			for _, fn := range fns {
				if err := fn(ranking_policy_version); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reportdatasetDescStatus is the schema descriptor for status field.
	reportdatasetDescStatus := reportdatasetFields[4].Descriptor()
	// reportdataset.DefaultStatus holds the default value on creation for the status field.
	reportdataset.DefaultStatus = reportdatasetDescStatus.Default.(string)
	// reportdataset.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	reportdataset.StatusValidator = reportdatasetDescStatus.Validators[0].(func(string) error)
	// reportdatasetDescCreatedAt is the schema descriptor for created_at field.
	reportdatasetDescCreatedAt := reportdatasetFields[6].Descriptor()
	// reportdataset.DefaultCreatedAt holds the default value on creation for the created_at field.
	reportdataset.DefaultCreatedAt = reportdatasetDescCreatedAt.Default.(func() time.Time)
	// reportdatasetDescID is the schema descriptor for id field.
	reportdatasetDescID := reportdatasetFields[0].Descriptor()
	// reportdataset.IDValidator is a validator for the "id" field. It is called by the builders before save.
	reportdataset.IDValidator = func() func(string) error {
		validators := reportdatasetDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	syncmetaFields := schema.SyncMeta{}.Fields()
	_ = syncmetaFields
	// syncmetaDescProvider is the schema descriptor for provider field.
	syncmetaDescProvider := syncmetaFields[0].Descriptor()
	// syncmeta.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	syncmeta.ProviderValidator = func() func(string) error {
		validators := syncmetaDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// syncmetaDescKind is the schema descriptor for kind field.
	syncmetaDescKind := syncmetaFields[1].Descriptor()
	// syncmeta.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	syncmeta.KindValidator = func() func(string) error {
		validators := syncmetaDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// syncmetaDescRecordCount is the schema descriptor for record_count field.
	syncmetaDescRecordCount := syncmetaFields[3].Descriptor()
	// syncmeta.DefaultRecordCount holds the default value on creation for the record_count field.
	syncmeta.DefaultRecordCount = syncmetaDescRecordCount.Default.(int)
}
