// Code generated by ent, DO NOT EDIT.

package evidence

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the evidence type in the database.
	Label = "evidence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldSensitivity holds the string denoting the sensitivity field in the database.
	FieldSensitivity = "sensitivity"
	// FieldCapturedBy holds the string denoting the captured_by field in the database.
	FieldCapturedBy = "captured_by"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldSourceURI holds the string denoting the source_uri field in the database.
	FieldSourceURI = "source_uri"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldCanonical holds the string denoting the canonical field in the database.
	FieldCanonical = "canonical"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the evidence in the database.
	Table = "evidences"
)

// Columns holds all SQL columns for evidence fields.
var Columns = []string{
	FieldID,
	FieldSystem,
	FieldSensitivity,
	FieldCapturedBy,
	FieldCapturedAt,
	FieldSourceURI,
	FieldVerified,
	FieldCanonical,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SystemValidator is a validator for the "system" field. It is called by the builders before save.
	SystemValidator func(string) error
	// SensitivityValidator is a validator for the "sensitivity" field. It is called by the builders before save.
	SensitivityValidator func(string) error
	// CapturedByValidator is a validator for the "captured_by" field. It is called by the builders before save.
	CapturedByValidator func(string) error
	// SourceURIValidator is a validator for the "source_uri" field. It is called by the builders before save.
	SourceURIValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Evidence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// BySensitivity orders the results by the sensitivity field.
func BySensitivity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSensitivity, opts...).ToFunc()
}

// ByCapturedBy orders the results by the captured_by field.
func ByCapturedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedBy, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// BySourceURI orders the results by the source_uri field.
func BySourceURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURI, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
