// Code generated by ent, DO NOT EDIT.

package syncmeta

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the syncmeta type in the database.
	Label = "sync_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldLastSync holds the string denoting the last_sync field in the database.
	FieldLastSync = "last_sync"
	// FieldRecordCount holds the string denoting the record_count field in the database.
	FieldRecordCount = "record_count"
	// Table holds the table name of the syncmeta in the database.
	Table = "sync_meta"
)

// Columns holds all SQL columns for syncmeta fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldKind,
	FieldLastSync,
	FieldRecordCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// DefaultRecordCount holds the default value on creation for the "record_count" field.
	DefaultRecordCount int
)

// OrderOption defines the ordering options for the SyncMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByLastSync orders the results by the last_sync field.
func ByLastSync(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSync, opts...).ToFunc()
}

// ByRecordCount orders the results by the record_count field.
func ByRecordCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordCount, opts...).ToFunc()
}
