// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CustomFieldDef is the predicate function for customfielddef builders.
type CustomFieldDef func(*sql.Selector)

// DimensionOption is the predicate function for dimensionoption builders.
type DimensionOption func(*sql.Selector)

// Evidence is the predicate function for evidence builders.
type Evidence func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// ItemAugment is the predicate function for itemaugment builders.
type ItemAugment func(*sql.Selector)

// OpportunityAssessment is the predicate function for opportunityassessment builders.
type OpportunityAssessment func(*sql.Selector)

// OpportunitySpec is the predicate function for opportunityspec builders.
type OpportunitySpec func(*sql.Selector)

// PortfolioDimension is the predicate function for portfoliodimension builders.
type PortfolioDimension func(*sql.Selector)

// ProfileAssignment is the predicate function for profileassignment builders.
type ProfileAssignment func(*sql.Selector)

// RankOverride is the predicate function for rankoverride builders.
type RankOverride func(*sql.Selector)

// Release is the predicate function for release builders.
type Release func(*sql.Selector)

// ReportDataset is the predicate function for reportdataset builders.
type ReportDataset func(*sql.Selector)

// SyncMeta is the predicate function for syncmeta builders.
type SyncMeta func(*sql.Selector)
